### ISSUE TITLE
Warnings about unknown URLs still produced when using allow_unknown_urls

### ISSUE THREAD

**Issue by shepmaster** [thoughtbot/capybara-webkit#837] opened 2015-09-13 21:36 UTC
I have this configuration:

```
Capybara::Webkit.configure do |config|
  config.allow_unknown_urls
  config.ignore_ssl_errors
end
```

But I still get a warning when running my tests:

```
Request to unknown URL: https://sub.localdomain.lan:449/api//pastry_kind/cake_color
To block requests to unknown URLs:
  Capybara::Webkit.configure do |config|
    config.block_unknown_urls
  end
To allow just this URL:
  Capybara::Webkit.configure do |config|
    config.allow_url("https://sub.localdomain.lan:449/api//pastry_kind/cake_color")
  end
To allow requests to URLs from this host:
  Capybara::Webkit.configure do |config|
    config.allow_url("sub.localdomain.lan")
  end
```

Looking at the implementation of `allow_unknown_urls`, it seems pretty straight-forward, so I must be doing something silly somewhere. Is there any reason that the global allow wouldn't work?

Other URLs that I access (there are multiple), all seem to work fine.

Versions:

```
Capybara-Webkit 1.7.0
Capybara 2.4.4
Ruby 2.2.3p173
Qt 4.8.6
```

**Comment by mhoran** [comment] 2015-09-16 02:17
Have you registered your own driver? It's possible that you're not providing the configuration object to the driver, which would result in the options being ignored. The driver must be registered with ``Capybara::Configuration.to_hash`` as the second argument. It's likely that you can eliminate any custom driver you were using as all the options were rolled in to the configuration object. See #806, where we intend to issue a warning for the issue.

**Comment by shepmaster** [comment] 2015-09-16 02:40
> Have you registered your own driver? 

Nope; I'm using whatever happens by requiring the gem. 

> It's possible that you're not providing the configuration object to the driver, which would result in the options being ignored.

Unlikely, as I can set the debug option here and it definitely takes effect. I also see certain blocked URL warnings disappear when I use the confit in my original comment. That's why it's such a strange occurrence.

**Comment by patrick99e99** [comment] 2015-09-16 18:45
I am also experiencing this.

**Comment by mhoran** [comment] 2015-09-23 03:21
Interesting. Could you extract a failing example that reproduces the issue? A complete example, including `spec_helper.rb` would be much appreciated. I haven't been able to reproduce this myself, but it's possible there's something I've missed.

**Comment by shepmaster** [comment] 2015-10-05 21:30
I'm still working on narrowing it down, but this does *not* reproduce when I run locally on OS X. However, when I run in an Ubuntu Docker image, it does reproduce. I'm seeing about making a smaller example.

**Comment by shepmaster** [comment] 2015-10-06 14:12
I've tracked it down a bit. Putting debug prints in [UnknownUrlHandler::reset](https://github.com/thoughtbot/capybara-webkit/blob/e9bd20a184d7e3c3b1aeebdceeaa66b2905afca2/src/UnknownUrlHandler.cpp#L71-L74), I see that it's being called.

I only see this being called from [WebPageManager::reset](https://github.com/thoughtbot/capybara-webkit/blob/e9bd20a184d7e3c3b1aeebdceeaa66b2905afca2/src/WebPageManager.cpp#L154). I *do* note that if I throw a `binding.pry` in my step I don't see this occurring.

My current hypothesis is this:

1. Access a page that performs AJAX calls
2. Do whatever capybara check we want.
3. Start to shut down the test, which presumably calls the [reset command](https://github.com/thoughtbot/capybara-webkit/blob/e9bd20a184d7e3c3b1aeebdceeaa66b2905afca2/src/Reset.cpp), which ultimately resets the allowed URLs.
4. The page still has active JS which triggers an AJAX request at this point.

Any thoughts?

**Comment by jferris** [comment] 2015-10-06 17:15
@shepmaster that's possible. Maybe we need to reorder our [`setup` function](https://github.com/thoughtbot/capybara-webkit/blob/master/src/WebPageManager.cpp#L147) to delete pending requests before changing other settings?

**Comment by TheTeaNerd** [comment] 2015-10-12 09:46
Just confirming that I'm seeing the same issue; I have explicitly allowed a URL which is requested via JS but I frequently receive a warning about blocking it. When I allow all unknown URLs the behaviour is unchanged, I still see a warning.

**Comment by thorn** [comment] 2015-11-20 08:05
I use this workaround:

```ruby
# spec/spec_helper.rb
Before('@javascript,@webkit') do
  page.driver.allow_url('*')
end
```

This gives me only one deprecation warning instead of many unknown url messages.

**Comment by Drakula2k** [comment] 2016-01-14 16:12
I'm experiencing the same issue, seems it's not just showing these warnings, but also resets all custom webkit driver settings for requests on point 4. It caused hangs for my case, because my webkit settings were reseted, so maybe related to #623. Also #816 looks like the same issue. 

As a temporary workaround I disabled the reset method on capybara, similar to this  http://stackoverflow.com/a/30809650/600638

**Comment by steakchaser** [comment] 2016-01-14 22:34
Same issue here.  Capybara `2.4.4`, Capybara Webkit `1.7.1`.

**Comment by lucasklaassen** [comment] 2016-01-23 23:23
Same issue here. Capybara 2.4.4, Capybara Webkit 1.7.1.

**Comment by dg-ratiodata** [comment] 2016-03-01 09:24
Any progress on this?

**Comment by jferris** [comment] 2016-03-01 19:20
I haven't been able to work on this yet.

**Comment by lucasklaassen** [comment] 2016-03-09 21:39
@jferris any ETA?

**Comment by jferris** [comment] 2016-03-09 22:03
@lucasklaassen I can't provide an ETA, since I work on capybara-webkit during spare time unless I'm encountering a bug I have to fix for my own work. I think this is likely the highest priority issue, so I'll work on this next time I have available for capybara-webkit.

If somebody look at some of the earlier suggestions and put together a pull request, that would take me less time than writing it myself, so it could potentially get merged sooner.

**Comment by lucasklaassen** [comment] 2016-03-30 17:39
@jferris just pinging you about this again for any updates? Your work on this project is much appreciated :)

**Comment by jferris** [comment] 2016-04-05 18:32
I submitted #895 which I believe will resolve the race condition.

**Comment by jferris** [comment] 2016-04-05 18:32
@shepmaster @lucasklaassen could one of you test out that branch to see if it resolves your issue? I still haven't been able to reproduce this locally.

**Comment by shepmaster** [comment] 2016-04-05 18:54
@jferris Sorry to disappoint, but I've moved on from the job where I had those tests, so I doubt I'll be of much help in reproducing. The diff appears sane, for what that's worth. :smile_cat:

**Comment by lucasklaassen** [comment] 2016-04-05 19:21
@jferris I unpacked the gem in a 'workspace' folder in my project and referenced the path it in my gemfile. I made the change from the PR you put up, ran bundle install and then ran bundle exec rspec. The alert messages for "Request to unknown URL" still appear even though I have the following code in my spec_helper.rb

```
Capybara::Webkit.configure do |config|
  config.allow_unknown_urls
end
```

**Comment by jferris** [comment] 2016-04-12 15:47
@lucasklaassen could you include the relevant parts of your configuration? Things like `spec_helper.rb`, `rails_helper.rb`, and things from `spec/support` may be useful. Also, a copy of your debug log (`config.debug = true`) may be useful.

**Comment by lucasklaassen** [comment] 2016-04-12 16:07
spec_helper.rb:
```
require 'capybara/rspec'
require 'pry'
require 'selenium-webdriver'
require 'byebug'
require 'capybara/webkit'
require 'yaml'
require 'helpers/session_helpers'
require 'helpers/web_helpers'
require 'helpers/wait_for_ajax'
require 'faker'

SPEC_ROOT=File.expand_path(File.dirname(__FILE__) + '/../')

Capybara.default_driver = :webkit
Capybara.javascript_driver = :webkit
options = {js_errors: false, debug: false, skip_image_loading: true, ignore_ssl_errors: true, allow_unknown_urls: true}
Capybara.register_driver :webkit do |app|
  Capybara::Webkit::Driver.new(app, options)
end

Capybara::Webkit.configure do |config|
  config.allow_unknown_urls
end

Capybara.default_max_wait_time = 10

RSpec.configure do |config|

  config.after(:all) do
    # Destroy fixtures
  end
  config.around(:each) do |example|
    begin
      example.run
    rescue Exception => ex
      save_and_open_page
      raise ex
    end
  end

  config.include WaitForAjax, type: :feature
end
```

I am not using rails for this project so I don't have a rails_helper and I do not have a spec/support folder.

**Comment by jferris** [comment] 2016-04-12 20:02
If you register your own `Capybara::Webkit::Driver`, it won't pick up options from `Capybara::Webkit.configure`. You can get the configuration Hash from `Capybara::Webkit::Configuration.to_hash`, which you can merge with other options if you'd like.

Note that this option is being deprecated shortly. You should be able to configure any options using `configure` block without registering your own driver.

I'm going to close this, as it seems like the race condition leading to this bug has been fixed. Please continue to comment or ask questions if you have any.

**Closed by jferris** 2016-04-12 20:02 UTC
Labels: bug
