### ISSUE TITLE
Makefile doesn't quote paths with spaces.

### ISSUE THREAD

**Issue by Oshuma** [thoughtbot/capybara-webkit#707] opened 2015-01-13 17:27 UTC
This is causing the build to fail, since it's trying to use a path with a space.

capybara-webkit v0.12.1
Ruby v2.0.0p481
OSX Yosemite 10.10.1

Note the line:  `/bin/sh: /Volumes/Macintosh: No such file or directory` where the actual path is `/Volumes/Macintosh HD/`

-----

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/oshuma/.rbenv/versions/2.0.0-p481/bin/ruby -r ./siteconf20150113-82826-16gud6t.rb extconf.rb 
cd src/ && /usr/local/bin/qmake /Users/oshuma/.rbenv/versions/2.0.0-p481/gemsets/audiogon/gems/capybara-webkit-0.12.1/src/webkit_server.pro -spec /usr/local/Cellar/qt/4.8.6/mkspecs/macx-g++ -o Makefile.webkit_server
cd src/ && /Volumes/Macintosh HD/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server 
/bin/sh: /Volumes/Macintosh: No such file or directory
make: *** [sub-src-webkit_server-pro-make_default-ordered] Error 127

make "DESTDIR=" clean
cd src/ && /Volumes/Macintosh HD/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server clean
/bin/sh: /Volumes/Macintosh: No such file or directory
make: *** [sub-src-webkit_server-pro-clean-ordered] Error 127

make "DESTDIR="
cd src/ && /Volumes/Macintosh HD/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.webkit_server 
/bin/sh: /Volumes/Macintosh: No such file or directory
make: *** [sub-src-webkit_server-pro-make_default-ordered] Error 127

make failed, exit code 2

Gem files will remain installed in /Users/oshuma/.rbenv/versions/2.0.0-p481/gemsets/audiogon/gems/capybara-webkit-0.12.1 for inspection.
Results logged to /Users/oshuma/.rbenv/versions/2.0.0-p481/gemsets/audiogon/extensions/x86_64-darwin-14/2.0.0-static/capybara-webkit-0.12.1/gem_make.out
An error occurred while installing capybara-webkit (0.12.1), and Bundler cannot continue.
Make sure that `gem install capybara-webkit -v '0.12.1'` succeeds before bundling.

```

**Comment by Oshuma** [comment] 2015-01-13 17:28
I can go into `src/` and run `make -f Makefile.webkit_server` which compiles the extension just fine.

**Comment by Oshuma** [comment] 2015-01-13 17:38
Looking at `CapybaraWebkitBuilder.make_bin`, I was able to work around this issue by setting the `MAKE` env variable (quoting spaces).

**Comment by mhoran** [comment] 2015-01-15 01:52
I'm not sure why the make path is expanded in your case, as when the `MAKE` environment variable was introduced, `CapybaraWebkitBuilder.make_bin` was simplified to `make`, instead of `which make`.

Can you confirm that the `MAKE` environment variable was not set by something else in your environment? Setting `MAKE=make` should work just as well as a full, quoted path.

I've successfully installed capybara-webkit on many a "Macintosh HD", so I expect something else may be causing this issue. capybara-webkit 0.12.1 is quite old at this point, so I'd recommend trying a newer release if possible.

**Comment by jferris** [comment] 2015-01-15 16:57
I'm going to close this, since it's for a very old version and I'd prefer to concentrate on current bugs. If you're able to reproduce this on a recent version of capybara-webkit, please comment again.

**Closed by jferris** 2015-01-15 16:57 UTC

**Comment by NullVoxPopuli** [comment] 2015-01-29 15:19
I'm having a similar error with a fresh install on ubuntu

    $ gem install capybara-webkit -v '1.3.1'
    Building native extensions.  This could take a while...
    ERROR:  Error installing capybara-webkit:
      ERROR: Failed to build gem native extension.

        /home/me/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150129-17123-11p6l7f.rb extconf.rb
    cd src/ && ( test -e Makefile.webkit_server || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/me/.rvm/gems/ruby-2.1.5/gems/capybara-webkit-1.3.1/src/webkit_server.pro -spec linux-g++ -o Makefile.webkit_server ) && make -f Makefile.webkit_server 
    Project ERROR: Unknown module(s) in QT: webkitwidgets
    make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 3
    Command 'make' failed

    make "DESTDIR=" clean
    cd src/ && ( test -e Makefile.webkit_server || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/me/.rvm/gems/ruby-2.1.5/gems/capybara-webkit-1.3.1/src/webkit_server.pro -spec linux-g++ -o Makefile.webkit_server ) && make -f Makefile.webkit_server clean
    Project ERROR: Unknown module(s) in QT: webkitwidgets
    make: *** [sub-src-webkit_server-pro-clean-ordered] Error 3

    make "DESTDIR="
    cd src/ && ( test -e Makefile.webkit_server || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/me/.rvm/gems/ruby-2.1.5/gems/capybara-webkit-1.3.1/src/webkit_server.pro -spec linux-g++ -o Makefile.webkit_server ) && make -f Makefile.webkit_server 
    Project ERROR: Unknown module(s) in QT: webkitwidgets
    make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 3

    make failed, exit code 2

    Gem files will remain installed in /home/me/.rvm/gems/ruby-2.1.5/gems/capybara-webkit-1.3.1 for inspection.
    Results logged to /home/me/.rvm/gems/ruby-2.1.5/extensions/x86_64-linux/2.1.0/capybara-webkit-1.3.1/gem_make.out

**Comment by NullVoxPopuli** [comment] 2015-01-29 15:22
I have the same problem when I just do `gem install capybara-webkit`

Fetching: capybara-webkit-1.4.1.gem (100%)

**Comment by mhoran** [comment] 2015-01-29 15:49
@NullVoxPopuli, it looks like you do not have the required dependencies installed. This is a different issue. Check out the `.travis.yml` in the project root for an example of how to install the required dependencies on Ubuntu.

**Comment by NullVoxPopuli** [comment] 2015-01-29 15:57
Ah ok. running `sudo apt-get update && sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev` fixed the issue. thanks. :-)
