### ISSUE TITLE
EOFError in Xvfb with 1.5.1

### ISSUE THREAD

**Issue by jwilf** [thoughtbot/capybara-webkit#779] opened 2015-05-19 09:58 UTC
I'm running with cucumber and capybara-webkit under xvfb-run on Linux. With 1.5.0, my scenario passes. With 1.5.1, it fails as follows:

bundle exec xvfb-run -a cucumber -p production

Received "Reset()"
Started "Reset()"
      end of file reached (EOFError)

Failing Scenarios:
cucumber -p production features/foo_monitoring.feature:7 # Scenario: Clicking through app

1 scenario (1 failed)
7 steps (7 passed)
0m22.189s

I've set up my env like this:

Capybara.register_driver :webkit_ignore_ssl do |app|
  browser = Capybara::Webkit::Browser.new(Capybara::Webkit::Connection.new).tap do |browser|
    browser.ignore_ssl_errors
    browser.enable_logging if ENV['CAPYBARA_DEBUG']
  end
  Capybara::Webkit::Driver.new(app, :browser => browser)
end

Capybara.default_driver = :webkit_ignore_ssl

Capybara.default_wait_time = 10

Capybara.configure do |config|
  config.match = :one
  config.exact_options = true
  config.ignore_hidden_elements = true
  config.visible_text_only = true
end

So all the steps in the scenario pass, but the scenario fails because this EOFError occurs at the end of the scenario. 

If I run the same test with 1.5.0 on Linux, is passes. If I run the test with 1.5.1 locally on my Mac without Xvfb, it also passes. So the issue seems to occur only with 1.5.1 in Xvfb.

**Comment by mhoran** [comment] 2015-05-19 12:07
This is likely a duplicate of #777, related to f8f2048500f8157f2cd0b2038c4cfcf205aa1ccb. @jferris is working on a fix.

**Closed by mhoran** 2015-05-19 12:07 UTC

**Comment by tcoldmf** [comment] 2019-06-27 09:59
We have the same problem with 1.14.0
