### ISSUE TITLE
Screenshot message not being displayed on Capybara::Webkit::ClickFailed

### ISSUE THREAD

**Issue by drueck** [thoughtbot/capybara-webkit#721] opened 2015-02-05 22:04 UTC
I am trying to debug a ClickFailed issue and I read that the latest versions of capybara-webkit will automatically take a screenshot and output a message indicating where the screenshot is located. I am running capybara-webkit version 1.4.1 and capybara 2.4.4, and it doesn't seem to be outputting the message with the screenshot location.

Here's the output of one of my failing tests:

``` shell
davidco: ats ✹✭ (sort-pump-components) ✗ rspec ./spec/features/admin/manage_product_images_spec.rb:5                                                           
Run options: include {:locations=>{"./spec/features/admin/manage_product_images_spec.rb"=>[5]}}

Manage product images
  Set an image as the featured image (FAILED - 1)

Failures:

  1) Manage product images Set an image as the featured image
     Failure/Error: click_on "Make Featured Image"
     Capybara::Webkit::ClickFailed:
       Failed to find position for element /html/body/div[1]/div[2]/div/div/div[2]/div[@id='product-images-section']/div[@id='product-images']/div[2]/a[2]
     # ./spec/features/admin/manage_product_images_spec.rb:21:in `block (3 levels) in <top (required)>'
     # ./spec/features/admin/manage_product_images_spec.rb:19:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'

Finished in 10.11 seconds (files took 0.2712 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/features/admin/manage_product_images_spec.rb:5 # Manage product images Set an image as the featured image

Top 1 slowest examples (6.66 seconds, 65.9% of total time):
  Manage product images Set an image as the featured image
    6.66 seconds ./spec/features/admin/manage_product_images_spec.rb:5

Randomized with seed 49745

Coverage report generated for RSpec to /home/david/projects/ats/coverage. 204 / 293 LOC (69.62%) covered.
davidco: ats ✹✭ (sort-pump-components) ✗ 
```

Is there some configuration that needs to be set to get the screenshots to be taken automatically? Is there something I'm doing wrong? Thanks for the help.

If it matters, I'm running Ubuntu 14.04 64-bit and ruby 2.1.5.

**Comment by tsujigiri** [comment] 2015-03-20 13:04
I see this error when running this line:

```ruby
first('[data-toggle="fullscreen"]').click
```

I tried different versions of the selector (e.g. by class) and it doesn't help. I also checked with a co-worker what Qt-webkit version he is running, since for him the test passes. He has 4.8.6, while I have 5.4.1.

**Comment by mhoran** [comment] 2015-03-20 13:11
There are two ways a click can fail: for elements with a known position, and those without. Elements with known positions may be unclickable due to overlapping elements. In this case, the position was unable to be calculated. When we can't find the element, we do not save a screenshot. You may want to try saving the screenshot yourself via `page.save_screenshot` to see if the element is displayed as expected.

**Comment by tsujigiri** [comment] 2015-03-20 13:14
My problem isn't the missing screenshot, but the error itself. I get it while my co-workers do not.
I'm sorry if I hijacked this issue. ;) Should I open a new one?

**Comment by tsujigiri** [comment] 2015-03-20 13:24
Trying it, I am indeed missing the element. When I try to only look it up without clicking it (`first('[data-toggle="fullscreen"]')`) I find it, though.

**Comment by tsujigiri** [comment] 2015-03-20 13:47
I downgraded Qt-webkit (i.e. I use the package the Wiki tells me to). Works.

**Comment by mhoran** [comment] 2015-03-20 13:52
Could you try to extract a failing test case (CSS, HTML, spec) which shows the failure? That will make it a lot easier to debug.

I've not upgraded to Qt 5.4 yet, but 5.2 has been working fine for me.

**Comment by tsujigiri** [comment] 2015-03-21 10:13
When tryng to reproduce the error I found out that it only happens when the link has no textual content in the actual HTML tag. The link our spec tests has no text but a span tag with a bootstrap glyphicon:

```html
<a data-toggle="fullscreen", href="#">
  <span class="glyphicon glyphicon-fullscreen"><span>
</a>
```

I was able to reproduce the error with this code:

**click.rb**
```ruby
require 'capybara-webkit'
Capybara.default_driver = :webkit
pwd = File.expand_path(File.join(__FILE__, '..'))
browser = Capybara.current_session

browser.visit("file://#{pwd}/page.html")
browser.find('#link').click
browser.find('#empty_link').click # <- fails with Capybara::Webkit::ClickFailed
```
**page.html**
```html
<a id="link" href="#">Click me!</a>
<a id="empty_link" href="#"></a>
```

**Comment by mhoran** [comment] 2015-03-26 15:51
Hey @tsujigiri. It is expected that an empty link would not be clickable. This is because clicks are implemented as native mouse events, which requires a clickable target and movement of a virtual mouse cursor. However, the Bootstrap (and Font Awesome) icons should work just fine. On my system, I'm able to click Boostrap and Font Awesome icons just fine. I'm running Debian Linux and Qt 5.3.2.

As a workaround, you may try to trigger the click via JavaScript. While not elegant, it should work. However, triggering a click via JavaScript may not fire other expected events, which can be a problem for JavaScript apps. Instead of calling `#click`, try `#trigger('click')`.

It's also possible that I'm able to click the icons because I have additional fonts installed. The Bootstrap font faces are overridden to prevent crashes on OS X. It may be possible to disable this override and click the icons on your system. Let me know if you'd like to explore that option.

**Comment by tsujigiri** [comment] 2015-03-26 16:05
I solved this for me (and now) by downgrading Qt-webkit. It seems like it is the glyphicon spans that stopped working in Qt 5.4's webkit, then. As mentioned, I didn't see the icons in the screenshot I did with Qt 5.4's webkit, either.

**Comment by mhoran** [comment] 2015-03-26 16:47
Interesting. I just installed Qt 5.4 on my system and could not reproduce. It is expected that the glyphicons would not show up in the screenshot, as the font face is overridden in capybara-webkit. However, there should still be a clickable area.

I tried this with the latest version of Bootstrap, so perhaps there's a difference in the CSS between the latest version and what you depend on. Aside from that, I'm at a loss as to what may be causing the issue.

**Comment by nritholtz** [comment] 2015-04-13 13:28
I hate to be the +1, but same issue with glyphicon calendar.

```
Started "Version()"
Finished "Version()" with response "Success(Qt: 5.4.0
WebKit: 538.1
QtWebKit: 5.4.0)"
Wrote response true "Qt: 5.4.0
WebKit: 538.1
QtWebKit: 5.4.0"
Capybara: 2.4.1
capybara-webkit: 1.3.0
Qt: 5.4.0
WebKit: 538.1
QtWebKit: 5.4.0
```

I had same exact environment between my Ubuntu desktop and Ubuntu server. Only difference was I was running the test on my CI with `xvfb-run` and the error I was receiving was:
```
Failed to click element /html/body/div[2]/main/div[1]/div/div[@id='create-ticket-widget']/div[2]/div[@id='ticket-form-container']/div[@id='call_issue_ticket-container']/form[@id='call_issue_ticket-form']/fieldset[@id='call-issue-ticket']/div[@id='sample-numbers-table']/div/table/tbody/tr[2]/td[3]/div/span/i because of overlapping element /html/body/div[2]/main/div[1]/div/div[@id='create-ticket-widget']/div[2]/div[@id='ticket-form-container']/div[@id='call_issue_ticket-container']/form[@id='call_issue_ticket-form']/fieldset[@id='call-issue-ticket']/div[@id='sample-numbers-table']/div/table/tbody/tr[2]/td[3]/div/span at position 1270, 524; 
```
However using @mhoran's tip with `#trigger('click')` worked fine. Very strange that it works fine on my desktop, but I'm only seeing issues on my Ubuntu Server CI.

**Comment by calleerlandsson** [comment] 2015-06-12 12:34
@mhoran Is there anything I can do to move this forward or is this a Qt issue?

**Comment by mhoran** [comment] 2015-06-14 14:56
I've been unable to reproduce this issue with either `glyphicon-calendar` or `glyphicon-fullscreen` and Qt 5.4.2 on Linux (Debian Jessie with Qt installed via the official installer.)

My example app is at https://github.com/mhoran/capybara-webkit-demo/. See `spec/features/fonticon_spec.rb`. I'd be interested to know if others see a failure on their platform running the same spec, or if there's some other difference between my repro attempt and the actual test failure.

**Comment by nritholtz** [comment] 2015-06-18 20:32
Well @mhoran, I actually ran your exact scenario on my Ubuntu Server CI and it failed:
```
nritholtz@catqa01:~/capybara-webkit-demo$ xvfb-run bundle exec rspec spec/features/fonticon_spec.rb
Rack::File headers parameter replaces cache_control after Rack 1.5.
F

Failures:

  1) visiting a fonticon page should be able to click the fonticon
     Failure/Error: page.find('a').click
     Capybara::Webkit::ClickFailed:
       Failed to find position for element /html/body/div/a
     # ./spec/features/fonticon_spec.rb:10:in `block (2 levels) in <top (require                                                                                                                     d)>'

Finished in 3.46 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/features/fonticon_spec.rb:4 # visiting a fonticon page should be ab      
```

Now, when I change it to use `trigger('click')`, it works just fine:
```
nritholtz@catqa01:~/capybara-webkit-demo$ xvfb-run bundle exec rspec spec/features/fonticon_spec.rb
Rack::File headers parameter replaces cache_control after Rack 1.5.
.

Finished in 0.32939 seconds
1 example, 0 failures
```

**Comment by alestuber** [comment] 2016-05-17 21:16
+1

**Comment by jogaco** [comment] 2017-01-24 13:52
I can confirm it's also working on Ubuntu with `trigger('click')`

`
Source: qtwebkit-opensource-src
Version: 5.1.1-1ubuntu8
`

**Comment by twalpole** [comment] 2017-10-18 19:28
Closing due to age, and lack of a way to replicate.  We can reopen if this is still an issue and a way to replicate is provided

**Closed by twalpole** 2017-10-18 19:28 UTC
