### ISSUE TITLE
redirects are causing capybara-webkit to hang 

### ISSUE THREAD

**Issue by catmando** [thoughtbot/capybara-webkit#873] opened 2016-01-11 20:28 UTC
Everything works fine with Selenium ff, but with webkit the tests run successfully, and then it hangs.  You then have to hit ctrl-c twice. 

Latest capybara-webkit, qt etc.

``` ruby
    it 'redirects an existing logged in user to the dashboard' do
      user = FactoryGirl.create :user
      login(user, then_visit: "/")
      # normally we would do a find at this point, but to simplify I am just doing a sleep.
      sleep(10) # if this line is removed the test will fail because dashboard
      # is not loaded.  But the rspec will terminate.   If this line is executed, and the delay
      # is long enough to allow the page to load, then the test will "pass" but rspec will
      # not terminate.
      expect(page.current_path).to eq "/account/#{user.id}/dashboard"
    end
```

**Comment by catmando** [comment] 2016-01-11 21:34
Here are two logs:  The first is when there is a 10 second delay, long enough for the page to load.  The second is when there is a 1 second delay, and the page does not load (so the test fails, but rspec exits)

https://gist.github.com/catmando/81dafb5212e8163389bd

https://gist.github.com/catmando/264accacf25e98bcb179

**Comment by jferris** [comment] 2016-01-11 22:09
Can you include the versions you're using for Capybara? You can find this by running `puts page.driver.version`.

From the hanging log, it looks as though the webkit server processes all of its commands fully, including the reset command at the end of the spec.

If you hit `ctrl-c` once and wait long enough, does it exist with a backtrace?

From the current logs, it's not clear where it's waiting.

**Comment by catmando** [comment] 2016-01-11 22:13
Here is a clue (hopefully)

I made it so you could visit the "/account/#id/dashboard" page without logging in (just in test :-) and now it works...

So it seems have something to do with going the session page, logging in and then redirecting?

here is the code for "login"
```ruby 
  def login(user, opts = {})
    visit "/session/new#{'?return_to='+opts[:then_visit] if opts[:then_visit]}"
    fill_in "user_session[login]", with: user.login
    fill_in "user_session[password]", with: user.password
    click_button "mobile_login_submit"
  end

It never exits after 1 ctrl-c... you have to hit it twice

this is with Capybara: 2.5.0 (via the puts statement as you suggested)

**Comment by jferris** [comment] 2016-01-11 22:16
What were the other versions?

**Comment by catmando** [comment] 2016-01-11 22:17
capybara 2.5.0

**Comment by catmando** [comment] 2016-01-11 22:18
what other versions?  Not following you

**Comment by jferris** [comment] 2016-01-11 22:19
When you run `puts page.driver.version`, you should see a list of version numbers. For example, mine looks like this:

```
Capybara: 2.5.0
capybara-webkit: 1.7.1
Qt: 5.5.1
WebKit: 538.1
QtWebKit: 5.5.1
```

**Comment by catmando** [comment] 2016-01-11 22:19
sorry... version: Capybara: 2.5.0
capybara-webkit: 1.7.1
Qt: 5.5.0
WebKit: 538.1
QtWebKit: 5.5.0

**Comment by catmando** [comment] 2016-01-11 22:25
@jferris - thanks for looking at this with me... What I have just discovered is that if I change my login method from:

```ruby
  def login(user, opts = {})
    visit "/session/new#{'?return_to='+opts[:then_visit] if opts[:then_visit]}"
    fill_in "user_session[login]", with: user.login
    fill_in "user_session[password]", with: user.password
    click_button "mobile_login_submit"
  end
```

to

```ruby
  def login(user, opts = {})
    visit "/session/new"
    fill_in "user_session[login]", with: user.login
    fill_in "user_session[password]", with: user.password
    click_button "mobile_login_submit"
    sleep(10)
    visit opts[:then_visit] if opts[:then_visit]
  end
```

things seem to work fine

I wonder if by immediately doing a "visit" right after the login, it was confusing things?

**Comment by jferris** [comment] 2016-01-11 22:28
Okay, thanks. I don't know of any issues with those releases.

Doing consecutive visits *shouldn't* confuse things, but there's a lot of asynchronous behavior in the driver, so sometimes we find bugs with rapid fire requests. Generally, it tries to wait until requests are finished when doing things like clicking buttons, but JavaScript events sometimes load new pages in ways that are difficult to detect.

One thing that may reliable fix the issue is looking for something on the next page before trying to visit another. For example:

``` ruby
click_button "mobile_login_submit"

expect(page).to have_content("You are now logged in.")

visit next_url
```

**Comment by catmando** [comment] 2016-01-11 22:30
Interestingly enough just adding a sleep(10) to the end of the original method **did not** work.  So it does seem some how related to the controller redirecting (instead of the test case)

**Comment by catmando** [comment] 2016-01-11 22:36
And after some more experiments it seems that any of our pages that do redirects cause the problem...huh

**Comment by jferris** [comment] 2016-01-12 15:15
That's pretty odd. We have many examples of capybara-webkit following redirects successfully, so it must be something more specific.

Do you have a smaller example log where directly visiting a controller that redirects causes the tests to hang? The current example logs have a large number of errors and warnings which obscure what may actually be happening.

**Comment by catmando** [comment] 2016-01-12 16:28
yes I will whittle it down to a minimal example.

I turns out its not a redirect, but just javascript updating window.location.href.

**Comment by gregblass** [comment] 2016-01-19 23:06
I *may* be hitting the same issue using Turbolinks...

**Comment by Scong** [comment] 2016-04-01 20:04
We're having the same issue when trying to test logging in against an oauth provider

Capybara: 2.6.2
capybara-webkit: 1.9.0
Qt: 5.5.1
WebKit: 538.1
QtWebKit: 5.5.1

**Comment by catmando** [comment] 2016-04-03 00:48
Just an update on this (@scong you may be interested)

I got everything to work nicely be implementing a wait_for_ajax method, that we use whenever there are pending ajax requests.  I found this hint here:

https://spin.atomicobject.com/2012/04/27/intermittent-test-failures/

**Comment by zacharyjt** [comment] 2017-07-18 21:32
I believe I have run into this issue as well.  If I run certain tests individually, they will pass, but rspec does not fully shut down.... I have to ctrl+c twice.  When I run the full suite, it will hang part of the way through, once it finishes the file with the offending tests.  The offending tests contain a visit to a page that has some interesting redirects going on.  I don't know all the inner workings of the redirects, but I have narrowed down the test behavior that causes the issue for me:
```
scenario 'test passes and doesn't hang' do
  # general setup
  using_session :viewer do
    visit page_with_redirect
    expect(page).to have_text 'test'
  end
end

scenario 'test passes, but hangs afterward' do
  # general setup
  using_session :viewer do
    visit page_with_redirect
    expect(page).to have_text 'test'
    visit page_with_redirect
    expect(page).to have_text 'other text'
  end
end
```
Fortunately, I have found I can workaround the hanging issue by inserting a `Capybara.reset_session!` between visits.

**Comment by twalpole** [comment] 2017-07-18 21:39
@zacharyjt What type of redirects are being done?  A self-contained reproducible example of this is really needed for it to be fixed.

**Comment by zacharyjt** [comment] 2017-07-28 17:05
@twalpole I dug into this with the engineers, and found it actually has to do with “beforeunload” on window that fires an ajax request.  We have this bit of code in a file that tracks time users spend on a page:
```
$(window).bind('beforeunload', function() {
    $.ajax({
      url: '/event.json',
      type: 'POST',
      dataType: 'json',
      data: { time: {}, id: 1 }
    })
} );
```
The issue for me occurs in the scenario I outlined above, but just replace `page_with_redirect` with `page_with_tracking`.  There are a number of additional workarounds I have found:
* Insert a `sleep 30` after the first `visit` and `expect()`
* Empty the data key: `data: {}`
* Do an 'unbind': `page.execute_script('$(window).unbind("beforeunload");')`
* Make the ajax request synchronous: `async: false`
* Make it a GET request: `type: 'GET'`

**Comment by twalpole** [comment] 2017-07-28 17:34
@zacharyjt Ok -- I can understand why your third and fourth workarounds could potentially make a difference since they stop the request completely and prevent unload from happening until the request is completed respectively.  The 2nd and fifth could just be speeding up the response to the request enough that it's done before unload actually happens (assuming the handler checks for `data` and does nothing when empty and a `GET` request isn't accepted so it quickly errors).  The first workaround doesn't really make a lot of sense though.

**Comment by twalpole** [comment] 2017-07-28 18:33
@zacharyjt What version QtWebkit did you build capybara-webkit with?

**Comment by zacharyjt** [comment] 2017-07-31 16:27
@twalpole [Here](https://gist.github.com/zacharyjt/6a5c978c56f29c236a93ed1266a32823) is the debug output of a hanging test.  The test I ran was:
```
scenario 'test' do
  visit '/documents/1'
  expect(page).to have_text 'Blank Proposal'
  visit '/documents/1'
  expect(page).to have_text 'Blank Proposal'
end
```
Here are my versions:
Capybara: 2.12.1
capybara-webkit: 1.14.0
Qt: 5.5.1
WebKit: 538.1
QtWebKit: 5.5.1

**Comment by twalpole** [comment] 2017-11-09 02:02
Closing since no reproducible example has been provided.   If/when one is we can reopen.

**Closed by twalpole** 2017-11-09 02:02 UTC
