### ISSUE TITLE
how to find to get the result in multiline text?

### ISSUE THREAD

**Issue by danilvoe** [thoughtbot/capybara-webkit#913] opened 2016-05-06 06:33 UTC
There's a html code

```
<p>
test text
<br/>
test2
<p/>
```

When performing the method:

`.find(:xpath, "/html/p").text`

result:

`test text test2`

How can I get the "two lines"

```
test text
test2
```

**Comment by jferris** [comment] 2016-05-09 15:50
We don't have an API for formatting text from the page. Getting the text is largely intended to allow looking for specific substrings. Also, if you're verifying that content is present, I highly recommend using `have_text` or `have_css("...", text: "...")` to avoid asynchronous issues.

If you could explain more about why you need to have the newline present in the resulting text, I might have more suggestions.

**Comment by danilvoe** [comment] 2016-05-10 05:50
capybara-web use to parse site, you respectively receive the text as its site the user sees. Actually I had already solved the problem by getting the data in html tags and subsequent processing. But I would like to see just a method that returns the text to be broken into lines ... while parsing sites is not exactly employment capybara

**Comment by jferris** [comment] 2016-06-02 14:12
If you wanted to put together a pull request that changed how the `text` result was formatted, I'd be open to that as along as it didn't introduce too much complexity or bring us further away from what Selenium does.

I'm going to close this issue, as it's not a bug in capybara-webkit and I don't plan on implementing this feature myself, but please continue to comment if you have further thoughts or questions.

**Closed by jferris** 2016-06-02 14:12 UTC
