### ISSUE TITLE
visit(url) hangs w/ EventSource

### ISSUE THREAD

**Issue by obfusk** [thoughtbot/capybara-webkit#597] opened 2013-12-05 11:12 UTC
My findings: https://gist.github.com/obfusk/7803381.
PhantomJS issue: ariya/phantomjs#11816.

\- Felix

**Comment by volodymyr-mykhailyk** [comment] 2015-01-28 16:12
This issue is still reproducible. It dont allow to properly test applications with EventSource functionality :(

**Comment by twalpole** [comment] 2017-10-18 18:15
Closing due to age and the fact this is probably a Qt limitation

**Closed by twalpole** 2017-10-18 18:15 UTC
