### ISSUE TITLE
capybara-webkit not working with qt55 from linuxbrew

### ISSUE THREAD

**Issue by ericenns** [thoughtbot/capybara-webkit#920] opened 2016-05-27 15:11 UTC
I get the following error message when trying to build capybara-webkit with qt55 from linuxbrew

    gem install capybara-webkit -v '1.10.1'
    Building native extensions.  This could take a while...
    ERROR:  Error installing capybara-webkit:
            ERROR: Failed to build gem native extension.

        /home/ericenns/.rvm/rubies/ruby-2.1.2/bin/ruby -r ./siteconf20160527-1120-e2tlo1.rb extconf.rb
    cd src/ && ( test -e Makefile.webkit_server || /home/ericenns/.linuxbrew/bin/qmake /home/ericenns/.rvm/gems/ruby-2.1.2/gems/capybara-webkit-1.10.1/src/webkit_server.pro -o Makefile.webkit_server ) && make -f Makefile.webkit_server 
    Project ERROR: Unknown module(s) in QT: webkitwidgets
    Makefile:42: recipe for target 'sub-src-webkit_server-pro-make_first-ordered' failed
    make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 3
    Command 'make' failed

    make "DESTDIR=" clean
    cd src/ && ( test -e Makefile.webkit_server || /home/ericenns/.linuxbrew/bin/qmake /home/ericenns/.rvm/gems/ruby-2.1.2/gems/capybara-webkit-1.10.1/src/webkit_server.pro -o Makefile.webkit_server ) && make -f Makefile.webkit_server clean
    Project ERROR: Unknown module(s) in QT: webkitwidgets
    Makefile:54: recipe for target 'sub-src-webkit_server-pro-clean-ordered' failed
    make: *** [sub-src-webkit_server-pro-clean-ordered] Error 3

    make "DESTDIR="
    cd src/ && ( test -e Makefile.webkit_server || /home/ericenns/.linuxbrew/bin/qmake /home/ericenns/.rvm/gems/ruby-2.1.2/gems/capybara-webkit-1.10.1/src/webkit_server.pro -o Makefile.webkit_server ) && make -f Makefile.webkit_server 
    Project ERROR: Unknown module(s) in QT: webkitwidgets
    Makefile:42: recipe for target 'sub-src-webkit_server-pro-make_first-ordered' failed
    make: *** [sub-src-webkit_server-pro-make_first-ordered] Error 3

    make failed, exit code 2

    Gem files will remain installed in /home/ericenns/.rvm/gems/ruby-2.1.2/gems/capybara-webkit-1.10.1 for inspection.
    Results logged to /home/ericenns/.rvm/gems/ruby-2.1.2/extensions/x86_64-linux/2.1.0/capybara-webkit-1.10.1/gem_make.out

Here is proof that it is actually using qt 5.5.1:

    qmake -v
    QMake version 3.0
    Using Qt version 5.5.1 in /home/ericenns/.linuxbrew/Cellar/qt55/5.5.1/lib

**Comment by jferris** [comment] 2016-05-31 14:22
> Project ERROR: Unknown module(s) in QT: webkitwidgets

It looks like you haven't installed QtWebKit. I'm not familiar with linuxbrew, and it looks like nobody has added instructions to the [wiki page](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit) yet, so you may be the first brave soul to compile capybara-webkit on that distro.

Many distros don't include QtWebKit with the base Qt package, so it's likely there's another package you need to install. If you find it, it would be very helpful to future users if you could update the Wiki page with your findings.

I'm going to close this issue, as it's not a bug in capybara-webkit and we don't have the resources to learn to compile on every system. However, please feel free to continue commenting and asking questions.

**Closed by jferris** 2016-05-31 14:22 UTC

**Comment by ericenns** [comment] 2016-05-31 15:55
linuxbrew is a port of homebrew for all linux distributions. The qt55 package is supposed to install the webkit plugin, but upon further inspection it wasn't doing this and also not throwing any error messages. I ended up getting it to work my compiling qt by hand.
