### ISSUE TITLE
Tests hang when using webkit as the javascript driver

### ISSUE THREAD

**Issue by LukasBeaton** [thoughtbot/capybara-webkit#623] opened 2014-02-27 22:26 UTC
I am experiencing an issue where Capybara hangs when I try to run tests with the webkit javascript driver.

Everything works fine when running tests with Firefox, but I would prefer to run them with webkit.

I noticed there was an issue over a year ago regarding hanging, but it has since been closed. Please let me know if you need any more info and how I can help.

**Comment by LaurMo** [comment] 2015-01-04 22:34
@LukasBeaton @risinglf @MinutemanZ @feifanzhou I'm seeing a similar problem and am curious if you ended up finding a solution. Thanks!

**Comment by MinutemanZ** [comment] 2015-01-05 00:15
@LaurMo I ended up using capybara-webkit instead.

**Comment by manmartinez** [comment] 2015-02-05 19:43
@LaurMo @risinglf @MinutemanZ @feifanzhou Did you guys ever figure this out? I'm upgrading a rails 3 app to rails 4 and all capybara-webkit tests are failing now, here's my setup:

```
Mac OS X 10.9.5
QMake version 2.01a
Using Qt version 4.8.6
```

On my Gemfile.lock:
```
capybara (2.4.4)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
capybara-webkit (1.4.1)
      capybara (>= 2.3.0, < 2.5.0)
      json
rspec (2.12.0)
      rspec-core (~> 2.12.0)
      rspec-expectations (~> 2.12.0)
      rspec-mocks (~> 2.12.0)
rspec-core (2.12.2)
rspec-expectations (2.12.1)
      diff-lcs (~> 1.1.3)
rspec-mocks (2.12.2)
rspec-rails (2.12.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 2.12.0)
      rspec-expectations (~> 2.12.0)
      rspec-mocks (~> 2.12.0)
```

And here's the output using `:webkit_debug`

```
Finished "EnableLogging()" with response "Success()" 
Wrote response true "" 
Received "SetUnknownUrlMode(block)" 
Started "SetUnknownUrlMode(block)" 
Finished "SetUnknownUrlMode(block)" with response "Success()" 
Wrote response true "" 
Received "Visit(http://127.0.0.1:55127/products/trunk)" 
Started "Visit(http://127.0.0.1:55127/products/trunk)" 
Load started 
"Visit(http://127.0.0.1:55127/products/trunk)" started page load 
Started request to "http://127.0.0.1:55127/products/trunk" 
Finished "Visit(http://127.0.0.1:55127/products/trunk)" with response "Success()" 
Started request to "http://127.0.0.1:55127/assets/store/all.css" 
Started request to "http://127.0.0.1:55127/assets/store/all.js" 
Started request to "http://127.0.0.1:55127/assets/jquery.zclip.js" 
Started request to "http://127.0.0.1:55127/assets/jquery.ui.js" 
Started request to "http://127.0.0.1:55127/assets/jquery.fancybox.js" 
Received 200 from "http://127.0.0.1:55127/products/trunk" 
Received 200 from "http://127.0.0.1:55127/assets/store/all.css" 
Received 200 from "http://127.0.0.1:55127/assets/store/all.js" 
Received 200 from "http://127.0.0.1:55127/assets/jquery.zclip.js" 
Received 200 from "http://127.0.0.1:55127/assets/jquery.ui.js" 
Received 200 from "http://127.0.0.1:55127/assets/jquery.fancybox.js" 
Started request to "http://127.0.0.1:55127/assets/store/bg.jpg" 
Started request to "http://127.0.0.1:55127/assets/sprites/close_zoom.png" 
Started request to "http://127.0.0.1:55127/assets/store/mack_weldon_logo.png" 
Started request to "http://127.0.0.1:55127/assets/admin/progress.gif" 
Started request to "http://127.0.0.1:55127/assets/store/black_px.png" 
Started request to "http://127.0.0.1:55127/store/mack_weldon_logo.png" 
Started request to "http://127.0.0.1:55127/assets/size_chart.png" 
Started request to "http://127.0.0.1:55127/assets/noimage/product.png" 
Started request to "http://127.0.0.1:55127/images/products/pdp_images/1/mini/M00000-BN_1.png?1423164886" 
Started request to "http://127.0.0.1:55127/images/products/pdp_images/2/mini/M00000-BN_2.png?1423164888" 
Started request to "http://127.0.0.1:55127/images/products/pdp_images/3/mini/M00000-BN_1.png?1423164890" 
Started request to "http://127.0.0.1:55127/images/products/pdp_images/4/mini/M00000-BN_2.png?1423164893" 
Started request to "http://127.0.0.1:55127/images/products/pdp_images/5/mini/M00000-BW_1.png?1423164895" 
Started request to "http://127.0.0.1:55127/images/products/pdp_images/6/mini/M00000-BW_2.png?1423164897" 
Started request to "http://127.0.0.1:55127/images/products/pdp_images/7/mini/M00000-BW_1.png?1423164899" 
Started request to "http://127.0.0.1:55127/images/products/pdp_images/8/mini/M00000-BW_2.png?1423164901" 
Started request to "http://127.0.0.1:55127/assets/sprites/zoom.jpg" 
Started request to "http://127.0.0.1:55127/images/option_value/1/image/normal/blue_night_swatch.jpg?1423164885" 
Started request to "http://127.0.0.1:55127/images/option_value/2/image/normal/blue_night_swatch.jpg?1423164885" 
Started request to "http://127.0.0.1:55127/assets/dropdown_lg.jpg" 
Started request to "http://127.0.0.1:55127/assets/thank_you.png" 
Started request to "http://127.0.0.1:55127/assets/icon_white_vimeo.png" 
Started request to "http://127.0.0.1:55127/assets/icon_white_twitter.png" 
Started request to "http://127.0.0.1:55127/assets/icon_white_facebook.png" 
Started request to "http://127.0.0.1:55127/assets/icon_white_pinterest.png" 
Started request to "http://127.0.0.1:55127/assets/logo_black.jpg" 
Started request to "http://127.0.0.1:55127/products/products/pdp_images/1/normal/M00000-BN_1.png?1423164886" 
Received 200 from "http://127.0.0.1:55127/assets/admin/progress.gif" 
Received 200 from "http://127.0.0.1:55127/assets/sprites/close_zoom.png" 
Received 200 from "http://127.0.0.1:55127/assets/store/black_px.png" 
Received 200 from "http://127.0.0.1:55127/assets/store/mack_weldon_logo.png" 
Received 200 from "http://127.0.0.1:55127/assets/store/bg.jpg" 
Started request to "http://127.0.0.1:55127/" 
Received 302 from "http://127.0.0.1:55127/store/mack_weldon_logo.png"
```

The test just hangs and crashes, returning the prompt without any output. I've found everything works up until I use `expect`

**Comment by Intrepidd** [comment] 2015-02-09 16:45
I have this issue too. Works locally but hangs on CI server

**Comment by mhoran** [comment] 2015-02-10 22:53
@manmartinez, I'd recommend upgrading Qt to 5.3 at least. There are many known issues with Qt 4.8. I haven't seen a hang myself since upgrading to 5.3.

It'd also be useful if you could extract a simple failing test case that exhibits this behavior. I know that may take some work, but it's truly difficult for us to replicate what may be causing the hang without an example.

One interesting thing I see in your case is that an image was redirected, which is the last thing that shows before the hang. I can't imagine any issues there, but it may be worth testing out.

It's also interesting that you get dropped back on the command line after the hang. This is something I've never seen. Typically when I get a hang, the spec will block forever. It may be worth seeing if the process actually crashes, or if something else has killed the tests.

**Comment by manmartinez** [comment] 2015-02-16 20:58
@mhoran Thanks Matthew I'll update my Qt version and post the results here, as for the test case I'll extract it when I've some free time

**Comment by LaurMo** [comment] 2015-02-26 05:11
Updated my Qt and capybara-webkit with no such luck...

**Comment by Intrepidd** [comment] 2015-02-26 07:06
I fixed this issue by stopping using page.evaluate_script when not
necessary, and use execute_script instead.

I remarked that it caused the driver to hand when returning large jquery
objects.

**Comment by jferris** [comment] 2015-02-26 15:13
We have timeouts around waiting for a page to load, but maybe we should have timeouts around commands in general.

@mhoran any thoughts?

**Comment by redbar0n** [comment] 2015-03-06 08:34
+1

I am getting this issue, or a very similar one. Here are my test code, and the :webkit_debug output:

https://gist.github.com/redbar0n/abb2524c9a883b11b44a

I tried downgrading to capybara-webkit 1.1.1 without success. No change at all.

Since downgrading was somewhat of a dependency hell, here are some gem versions that will work with 1.1.1 if you lock their versions like this, in your Gemfile:

  gem 'capybara-webkit', '1.1.1'
  gem 'capybara', '2.1.0'
  gem "rspec-rails", '2.14.1'

FWIW.

**Comment by mhoran** [comment] 2015-03-06 14:13
@jferris, seems reasonable. I had looked into that option when implementing the modal API, but it was easier to implement the timeout in Ruby than by modifying `TimeoutCommand`. I don't remember what the exact issue was at the time. It'd also be interesting to see what Selenium does in this case.

I think some confusion may arise from the fact that some commands may trigger an asynchrnous page load. The timeout may apply to the current command, or the next one, depending on whether or not a page load was triggered.

**Comment by redbar0n** [comment] 2015-03-11 07:37
Found the solution, and detailed it here: http://magnemg.tumblr.com/post/113251336220/how-to-solve-a-capybara-webkit-and-video-js

Hope this helps someone, it took me a lot of work to finally figure this one out, and get it working.

**Comment by Intrepidd** [comment] 2015-03-11 08:38
I read your article.

While qt 5.4 on mac definitely solves A LOT of things, I had also some hangs with it.

And btw, you have to ``brew link -f qt5`` to symlink qt5 binaries, as explained in the post install message :)

**Comment by redbar0n** [comment] 2015-03-11 08:47
Thanks, updated. I thought just symlinking the files Homebrew suggested would be enough, but I see that it symlinked even more files when I ran that command.

**Comment by redbar0n** [comment] 2015-03-11 09:20
Hm, after I run `brew link -f qt5` then Homebrew complains: 

```
Warning: Some keg-only formula are linked into the Cellar.
Linking a keg-only formula, such as gettext, into the cellar with
`brew link <formula>` will cause other formulae to detect them during
the `./configure` step. This may cause problems when compiling those
other formulae.

Binaries provided by keg-only formulae may override system binaries
with other strange results.

You may wish to `brew unlink` these brews:

    qt5
```

After running `brew unlink qt5` then Homebrew stops complaining, and my system seems to work fine.

Not exactly sure if I should leave it as that, or what.

Any comments?

**Comment by billywatson** [comment] 2015-03-11 14:28
I feel like if there are other hanging issues, we shouldn't nec. update the docs just yet to say "everyone switch to qt X.Y on OS X".  However, I feel you could add some docs on how to get capybara-webkit installing on OS X using qt 5.x. 

Is there a way to replicate some of these issues in an automated test, first before we declare victories?

Also, I wouldn't worry too much about that message you're getting in homebrew. If you're able to install capybara webkit without issue, then go for it.

**Comment by mhoran** [comment] 2015-03-11 14:46
Some of the issues we're aware of are difficult to reproduce, due to bugs in Qt, WebKit, or the Qt WebKit bridge. Some issues are more obvious, like missing JavaScript functionality due to the outdated WebKit runtime. Most of the time these issues are debugged on a case by case basis, but personally I've been running, and recommending others run, Qt 5 for almost two years.

We do intend to drop support for Qt 4.8 in the next major release (2.0). Codeship has already dropped Qt 4.8 in preference of 5, and Qt 5 is easily installed on other CI services (Travis CI -- see our .travis.yml.)

While it's surprisingly difficult to get Qt 5 running on a Mac via Homebrew, the Qt project distributes a binary installer which is quite easy to use on OS X. Once installed via the package, one simply needs to set the QMAKE environment variable bundle.

We're not going to require Qt 5 without a major version bump. The README does not specify a preferred Qt version, which as mentioned can differ based on the use case. However, Qt 5 is recommended as the first course of action when debugging crashes and broken features in capybara-webkit.

Install instructions are on our wiki, which is open to editing. We appreciate it when folks share their successes on the wiki, as it makes it easier for others to get started. Pull requests are also welcome for the README, if you think there are specific changes which can make installation more straight forward.

**Comment by redbar0n** [comment] 2015-03-23 10:35
@billywatson @mhoran 
Agree. Everyone shouldn't necessarily switch (as switching currently requires a full Xcode install, which is a 5 GB burden). Just a mention of the problem in the wiki page would have been sufficient for me. I added a section on the wiki now. Didn't want to add anything to the wiki before discussing it with you here, since you might have concerns. Next time I might be more bold and just edit the wiki off the bat. :-)

My test case was very simple: just trying to play a video on a page. The test code is given in the top of my [gist](https://gist.github.com/redbar0n/abb2524c9a883b11b44a). I would be happy to supply further details if someone wants to write a separate test for this in a capybara-webkit test suite.

**Comment by calleerlandsson** [comment] 2015-06-12 12:10
@mhoran Can this be issue be fixed by adding timeouts around commands or is upgrading to Qt 5 the only workaround?

**Comment by mhoran** [comment] 2015-06-12 12:15
Upgrading to Qt 5 may fix some instances of hanging tests, but we may still want to investigate extending our timeout functionality. I'm not sure what to do about this issue, though. It seems that some folks are still struggling with hanging tests, which could be due to outdated Qt versions, or some other issue we're not aware of. However, it's difficult to debug such issues without a reproducible test case. If anyone is able to extract such a failing test case, we'd be happy to look into the issue further.

**Comment by brauliobo** [comment] 2015-07-09 13:37
The tests are hanging here on lastest capybara-webkit (1.6.0) and capybara (2.4.4), with both qt 4.8.1 (see https://travis-ci.org/coletivoEITA/noosfero-ecosol/jobs/70221234) and qt 5.4.2 (from archlinux).

Here is the debug run on qt 5.4.2:
```
Received 304 from "http://localhost:33646/assets/assets/stylesheets/chat.self.css?body=1"
Received 304 from "http://localhost:33646/assets/assets/stylesheets/search.self.css?body=1"
Received 304 from "http://localhost:33646/assets/designs/icons/default/style.self.css?body=1"
Received 304 from "http://localhost:33646/assets/designs/icons/pidgin/style.self.css?body=1"
Received 304 from "http://localhost:33646/assets/designs/themes/noosfero/style.css"
Started request to "http://localhost:33646/assets/designs/themes/base/style.css"
Received 304 from "http://localhost:33646/assets/assets/stylesheets/tasks.self.css?body=1"
Received 304 from "http://localhost:33646/assets/assets/javascripts/tasks.self.js?body=1"
Received 304 from "http://localhost:33646/assets/designs/themes/base/style.css"
Page finished with true
Load finished
Started "Reset()"
Finished "Reset()" with response "Success()"
Wrote response true ""
Received "EnableLogging()"
Started "EnableLogging()"
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetUnknownUrlMode(block)"
Started "SetUnknownUrlMode(block)"
Finished "SetUnknownUrlMode(block)" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "FindXpath(/html/body/*)"
Started "FindXpath(/html/body/*)"
Finished "FindXpath(/html/body/*)" with response "Success()"
Wrote response true ""
FReceived "Header(Accept-Language, en)"
Started "Header(Accept-Language, en)"
Finished "Header(Accept-Language, en)" with response "Success()"
Wrote response true ""
.....Received "Visit(http://localhost:33646/account/logout)"
Started "Visit(http://localhost:33646/account/logout)"
Load started
"Visit(http://localhost:33646/account/logout)" started page load
Started request to "http://localhost:33646/account/logout"
Finished "Visit(http://localhost:33646/account/logout)" with response "Success()"
```

**Comment by brauliobo** [comment] 2015-07-09 15:00
Oh, it was a problem with `:transaction` and `DatabaseCleaner`. It seems it is not an option with capybara-webkit. Maybe a warning or an error should be printed if it is used?

**Comment by jferris** [comment] 2015-07-09 15:09
That's strange. Issues with transactions usually result in the data just not being available in the Capybara thread; I haven't seen it hang the server before.

> If I type control + c the tests continue to run.

What does it print after hitting <kbd>Ctrl</kbd>+<kbd>C</kbd>?

**Comment by brauliobo** [comment] 2015-07-09 15:21
> That's strange. Issues with transactions usually result in the data just not being available in the Capybara thread; I haven't seen it hang the server before.

Yeah, just switching to truncation made it run normally. I've also tried https://github.com/jnicklas/capybara#transactions-and-database-setup with no help.
The truncation setup that works: https://github.com/coletivoEITA/noosfero-ecosol/blob/f80313dce1295b7f50a68b877273ae56bff1ca94/features/support/javascript.rb
The transaction setup that hangs: https://github.com/coletivoEITA/noosfero-ecosol/blob/87801d77944261fa73681b4b08d8b3c53370b178/features/support/javascript.rb
(the `Cucumber::Rails::World.use_transactional_fixtures` doesn't make any difference)

> If I type control + c the tests continue to run.
> What does it print after hitting Ctrl+C?
It continues to run, but any succes, just failures and skips.

**Comment by iangreenleaf** [comment] 2015-08-28 04:43
FWIW, if you're using Postgres and sharing a database connection to work around transactions, if your threads make conflicting requests to the DB, Postgres may silently hang. So that could explain the symptoms you were seeing.

**Comment by franklingu** [comment] 2015-10-10 07:13
I run into this problem as well with Qt 4.8.6, capybara-webkit 1.7.1. Turns out that I am loading a very large video from other servers and that is slow itself. Simply block unkown that url worked for me

**Comment by manuelmeurer** [comment] 2015-12-26 17:55
Switching DatabaseCleaner from `transaction` to `truncation` solved this for me!

**Comment by arielvalentin** [comment] 2016-03-28 17:13
I have been wrestling with this same problem. We use a combination of `Cucumber`, `Capybara`, `DatabaseCleaner`, and `capybara-webkit` in our test suite. 

Every once and a while our build would timeout because our `cucumber` suite would pause. Our test suite has grown substantially in the past few months and we are starting to experience this problem regularly.  

At first, we were experiencing some issues with `DatabaseCleaner` and `cucumber-rails` where they were competing with each other to handle transactions, however once I fixed that issue I was able to produce the "hung" test. 

When the test hangs it seems like all of the threads/processes are still running however it seems like they are waiting on responses from each other.

I first checked for DB locks:
```
PG Locks  (3386 is psql PID)
x_test=# select datname, pid, application_name, query, xact_start, waiting, state from pg_stat_activity where pid != 3386;
  datname  | pid  |             application_name              |                                             query                                             | xact_start | waiting | state
-----------+------+-------------------------------------------+-----------------------------------------------------------------------------------------------+------------+---------+-------
 x_test | 1720 | /Users/ariel/.gem/ruby/2.1.5/bin/cucumber | xxxx |            | f       | idle
 x_test | 1731 | /Users/ariel/.gem/ruby/2.1.5/bin/cucumber | xxx                                |            | f       | idle
(2 rows)


x_test=# select * from pg_locks where pid != 3386;
 locktype | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction | pid | mode | granted | fastpath
----------+----------+----------+------+-------+------------+---------------+---------+-------+----------+--------------------+-----+------+---------+----------
(0 rows)
```

:cry: no... the DB has no locks... 

OK if they isn't stuck on DB deadlocks then what else are they doing. Since I am on a Mac I started by using `dtruss` on the `cucumber` ruby process:
```
$> sudo dtruss -p 1706 -f -l
 1706/0x944f:  sigprocmask(0x1, 0x0, 0x70000091F450)		 = 0x0 0
 1706/0x944f:  sigaltstack(0x0, 0x70000091F440, 0x70000091F450)		 = 0 0
 1706/0x942a:  select(0x15, 0x70000040FD3C, 0x70000040FDBC, 0x70000040FE3C, 0x70000040FEC0)		 = 0 0
 1706/0x942a:  sigprocmask(0x1, 0x0, 0x70000040FBC0)		 = 0x0 0
 1706/0x942a:  sigaltstack(0x0, 0x70000040FBB0, 0x70000040FBC0)		 = 0 0
 1706/0x942a:  select(0x15, 0x70000040FD3C, 0x70000040FDBC, 0x70000040FE3C, 0x70000040FEC0)		 = 0 0
 1706/0x942a:  sigprocmask(0x1, 0x0, 0x70000040FBC0)		 = 0x0 0
 1706/0x942a:  sigaltstack(0x0, 0x70000040FBB0, 0x70000040FBC0)		 = 0 0
 1706/0x942a:  select(0x15, 0x70000040FD3C, 0x70000040FDBC, 0x70000040FE3C, 0x70000040FEC0)		 = 0 0
 1706/0x942a:  sigprocmask(0x1, 0x0, 0x70000040FBC0)		 = 0x0 0
 1706/0x942a:  sigaltstack(0x0, 0x70000040FBB0, 0x70000040FBC0)		 = 0 0
```

It looks to be using a polling select; `lsof` shows we are talking to another process over TCP
```
mataleon:gust 15:05:51 (flaky/dbcleaner/115875867) asmvb$ sudo lsof -p 1706 | grep 15u
ruby    1706 ariel   15u   IPv4 0x35465c9f9e6697d3       0t0      TCP localhost:50132->localhost:50131 (ESTABLISHED)
```
OK that looks like `webkit_server` is listening...
```
mataleon:gust 14:04:29 (flaky/dbcleaner/115875867) asmvb$ lsof -Pnl +M -i4 | grep 50131
ruby      1706      502   15u  IPv4 0x35465c9f9e6697d3      0t0  TCP 127.0.0.1:50132->127.0.0.1:50131 (ESTABLISHED)
webkit_se 1724      502    9u  IPv4 0x35465c9f95b409e3      0t0  TCP 127.0.0.1:50131 (LISTEN)
webkit_se 1724      502   10u  IPv4 0x35465c9f970d30db      0t0  TCP 127.0.0.1:50131->127.0.0.1:50132 (ESTABLISHED)
```

Webkit `dtruss` just writing null bytes to a few places
```
ioctl(0x10, 0xC02869C9, 0x700000322498)          = -1 Err#82
write(0xC, "\0", 0x1)            = 1 0
select(0xC, 0x7FA993829F98, 0x7FA99382A228, 0x7FA99382A4B8, 0x0)                 = 1 0
workq_kernreturn(0x20, 0x0, 0x1)                 = 0 0
read(0xB, "\0", 0x10)            = 1 0
workq_kernreturn(0x20, 0x0, 0x1)                 = 0 0
read(0xB, "\0", 0x10)            = -1 Err#35
write(0xC, "\0", 0x1)            = 1 0
pselect(0xC, 0x7FA993829F98, 0x7FA99382A228)             = 1 0
read(0xB, "\0", 0x10)            = 1 0
read(0xB, "\0", 0x10)            = -1 Err#35
workq_kernreturn(0x20, 0x0, 0x1)                 = 0 0
workq_kernreturn(0x20, 0x0, 0x1)                 = 0 0
workq_kernreturn(0x20, 0x0, 0x1)                 = 0 0
close(0x10)              = 0 0
```

Let's use `gdb` just to make sure...

Ruby
```
(gdb) info threads
  Id   Target Id         Frame
  14   Thread 0x250f of process 1706 0x00007fff99a0407a in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
  13   Thread 0x230b of process 1706 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  12   Thread 0x220b of process 1706 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  11   Thread 0x210b of process 1706 0x00007fff99a052a2 in poll () from /usr/lib/system/libsystem_kernel.dylib
  10   Thread 0x200b of process 1706 0x00007fff99a04582 in __wait4 () from /usr/lib/system/libsystem_kernel.dylib
  9    Thread 0x1f0b of process 1706 0x00007fff99a05362 in read () from /usr/lib/system/libsystem_kernel.dylib
  8    Thread 0x1e0b of process 1706 0x00007fff99a0407a in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
  7    Thread 0x1d0b of process 1706 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  6    Thread 0x1c0b of process 1706 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  5    Thread 0x1b0b of process 1706 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  4    Thread 0x1a0b of process 1706 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  3    Thread 0x190b of process 1706 0x00007fff99a0407a in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
  2    Thread 0x180b of process 1706 0x00007fff99a04582 in __wait4 () from /usr/lib/system/libsystem_kernel.dylib
* 1    Thread 0x170b of process 1706 0x00007fff99a05362 in read () from /usr/lib/system/libsystem_kernel.dylib
(gdb)
```

Webkit
```
(gdb) info threads
  Id   Target Id         Frame
  15   Thread 0x2603 of process 1724 0x00007fff99a045e2 in __workq_kernreturn () from /usr/lib/system/libsystem_kernel.dylib
  14   Thread 0x2413 of process 1724 0x00007fff99a045e2 in __workq_kernreturn () from /usr/lib/system/libsystem_kernel.dylib
  13   Thread 0x230f of process 1724 0x00007fff999fdf72 in mach_msg_trap () from /usr/lib/system/libsystem_kernel.dylib
  12   Thread 0x220f of process 1724 0x00007fff99a04efa in kevent_qos () from /usr/lib/system/libsystem_kernel.dylib
  11   Thread 0x210f of process 1724 0x00007fff99a0407a in select$DARWIN_EXTSN () from /usr/lib/system/libsystem_kernel.dylib
  10   Thread 0x200f of process 1724 0x00007fff999fdf72 in mach_msg_trap () from /usr/lib/system/libsystem_kernel.dylib
  9    Thread 0x1f0f of process 1724 0x00007fff99a03d3e in __pselect () from /usr/lib/system/libsystem_kernel.dylib
  8    Thread 0x1e0f of process 1724 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  7    Thread 0x1d0f of process 1724 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  6    Thread 0x1c0f of process 1724 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  5    Thread 0x1b0f of process 1724 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  4    Thread 0x1a0f of process 1724 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  3    Thread 0x190f of process 1724 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
  2    Thread 0x180f of process 1724 0x00007fff99a03db6 in __psynch_cvwait () from /usr/lib/system/libsystem_kernel.dylib
* 1    Thread 0x170f of process 1724 0x00007fff99a045e2 in __workq_kernreturn () from /usr/lib/system/libsystem_kernel.dylib
```
:shrug: Not much I can gather from here either...

When I get more information I will share it in this thread. For now I have set the `timeout` property to 60 seconds, which seems to working properly because now the build continues to the next step when the thread is hung.

**Comment by arielvalentin** [comment] 2016-05-17 02:43
After I turned logging on
```
Received 0 from "http://127.0.0.1:9887/assets/application.css"
Page finished with true
Load finished
Page load from command finished
Wrote response false "{\"class\":\"TimeoutError\",\"message\":\"Request timed out after 15 second(s)\"}"
```

**Comment by wardnath** [comment] 2017-07-03 20:26
The `DatabaseCleaner` config block [here](https://github.com/DatabaseCleaner/database_cleaner/issues/273#issuecomment-106954432) stopped the tests hanging for me

**Comment by twalpole** [comment] 2017-10-18 19:32
Closing due to age.  If this is still an issue we can reopen when a way to replicate is provided.

**Closed by twalpole** 2017-10-18 19:32 UTC
