### ISSUE TITLE
Time inputs not triggering form onChange event

### ISSUE THREAD

**Issue by davidham** [thoughtbot/capybara-webkit#916] opened 2016-05-12 13:39 UTC
I have a Rails app with a React frontend. I have a form with a date input and two time inputs. Entering data in the form elements triggers an onChange event, which sets the values on an object that gets posted to Rails.

My test is failing because the values I fill in on the time inputs are not triggering the onChange event. Here is my test from Cucumber:

```
fill_in 'service_date', with:'2016-05-11'
select 'Patient Visit', from: 'service_type'
fill_in 'start_time', with: '08:33:00'
fill_in 'end_time', with: '13:47:00'

expect( find_field('start_time').value ).to eq('08:33:00')

fill_in 'travel_hours', with: '1'
fill_in 'travel_minutes', with: '23'

click_on 'Continue'
```

Here is the output of `page.control.driver`:

```
Capybara: 2.7.0
capybara-webkit: 1.10.1
Qt: 5.3.2
WebKit: 538.1
QtWebKit: 5.3.2
```

The `expect` in the middle passes, and if I screenshot the page, I can see the times entered in the control. However, I can also pass arbitrary text to the time controls (not just valid time strings). I have tried `fill_in` and `set()` and neither works. Is there a way to trigger the event manually, or is there another way to set values on time inputs?

P.S. The test fails, but when I try the functionality in desktop Chrome, it works.

**Comment by jferris** [comment] 2016-06-02 16:04
> My test is failing because the values I fill in on the time inputs are not triggering the onChange event. 

We fire the `change` event ourselves based on the input type. We currently don't have `time` included in our list of text inputs: https://github.com/thoughtbot/capybara-webkit/blob/master/src/capybara.js#L298

> However, I can also pass arbitrary text to the time controls (not just valid time strings).

It looks like the `time` input type isn't supported in most browsers, so it will fall back to a text input: http://caniuse.com/#feat=input-datetime

**Comment by davidham** [comment] 2016-06-02 16:37
Maybe something like how [how Modernizr does it](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/inputtypes.js)?

- If the control declares itself `input type="time"` set its value to an invalid time string
- Check its value
- If value is an empty string, it's a supported `time` control (since they're supposed to sanitize to "" per [WHATWG](https://html.spec.whatwg.org/multipage/forms.html#time-state-(type=time)))
- If the value is the supplied string, it fell back to a text input

**Comment by jferris** [comment] 2016-06-02 17:00
@davidham I'm not too concerned with supporting the time-specific features in capybara-webkit. I think we'd expect to set them as text values either way. I think the bug here is that we're not firing events on a text input.

**Comment by jferris** [comment] 2016-06-02 17:13
I looked at putting together a fix for this, but I was unable to reproduce the bug. It appears as though QtWebKit ignores the given type and reports `text` for input types it doesn't support, so the events are firing as expected for me with `time` and `date` inputs.

@davidham would you be able to put together a failing test or minimal example to reproduce this bug?

**Comment by davidham** [comment] 2016-06-03 14:01
Sure, I'll try putting something together later this afternoon.

**Comment by twalpole** [comment] 2017-10-18 18:41
Closing due to lack of response - we can reopen if/when a failing test is provided

**Closed by twalpole** 2017-10-18 18:41 UTC
Labels: bug
