### ISSUE TITLE
warning: constant ::Fixnum is deprecated in Ruby 2.4.0

### ISSUE THREAD

**Issue by ckundo** [thoughtbot/capybara-webkit#1015] opened 2017-07-06 19:21 UTC
We're running into a deprecation warning running our tests with capybara-webkit, using Ruby 2.4.0:

```
.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/capybara-webkit-1.1.0/lib/capybara/webkit/browser.rb:84: warning: constant ::Fixnum is deprecated
```

The warning is raised when calling `page.driver.browser.frame_focus` without any arguments. The call to `Fixnum` is here: https://github.com/thoughtbot/capybara-webkit/blob/master/lib/capybara/webkit/browser.rb#L87.

`Fixnum` and `Bignum` were deprecated with the release of Ruby 2.4.0, in favor of `Integer`, as announced here: https://www.ruby-lang.org/en/news/2016/12/25/ruby-2-4-0-released/

Here's the new function that doesn't throw a deprecation warning:

```ruby
def frame_focus(selector=nil)
  if selector.respond_to?(:base)
    selector.base.invoke('focus')
  elsif selector.is_a? Integer
    command("FrameFocus", "", selector.to_s)
  elsif selector
    command("FrameFocus", selector)
  else
    command("FrameFocus")
  end
end
```

Happy to open a PR, but first wanted to know if/how we can drive out the implementation with a test.

**Comment by twalpole** [comment] 2017-07-06 19:44
Quick question -- any reason you're running such an old capybara-webkit (the issue is still in the current release).  v 1.1.0  was released in 2013.

**Comment by mhoran** [comment] 2017-07-06 19:47
Seems like a refactor to me, @ckundo. Go ahead and send a PR. As soon as Ruby removes Fixnum, this will test itself!

**Comment by DannyBen** [comment] 2017-08-15 14:20
This issue is still present with version 1.14.0, and the culprit is [in this line][1].

The error:
```
/usr/lib/ruby/gems/2.4.0/gems/capybara-webkit-1.14.0/lib/capybara/webkit/browser.rb:87: warning: constant ::Fixnum is deprecated
```

As triggered by this cucumber stepdef:

```ruby
Then(/^(?:the )?iframe should contain "([^"]*)" (?:selector|element)$/) do |selector|
  expect(page).to have_selector 'iframe'
  within_frame find('iframe') do
    expect(page).to have_selector selector
  end
end
```

[1]: https://github.com/thoughtbot/capybara-webkit/blob/1617ee424c6b62177ad836126f83041999d6e986/lib/capybara/webkit/browser.rb#L87

**Comment by twalpole** [comment] 2017-10-18 19:42
Fixed in master

**Closed by twalpole** 2017-10-18 19:42 UTC
