### ISSUE TITLE
New Test Failures after 10.10.3 Yosemite Update

### ISSUE THREAD

**Issue by justin808** [thoughtbot/capybara-webkit#755] opened 2015-04-10 19:17 UTC
All the new failures are related to the use of jQuery DataTables.

For some reason, tests would previously wait until the table populated.

After the OS update, the table contains zero rows and the tests failed.

We've confirmed that 10.10.2 does not have this issue.

    gem 'capybara', '2.4.4'
    gem "capybara-webkit", '1.3.1'

Confirmed that this is still an issue with 

    gem "capybara-webkit", '1.5.0'

**Comment by jferris** [comment] 2015-04-10 21:23
I'm not familiar with jQuery DataTables. Could you provide some of the following?

* A log from the `:webkit_debug` driver
* Some example JavaScript which isn't working
* An example test which isn't working
* Some example markup from the UI which isn't working
* Any relevant application logs from failed test runs

Also, could you see if the tests are passing using the standard Selenium driver?

**Comment by justin808** [comment] 2015-04-11 02:02
@jferris I get errors from Selenium, but I'm not sure if they're the same. There's a couple of my team members working on getting some more information. Anybody else see any issues with Yosemite Mac OS 10.10.3?

**Comment by dboyd68** [comment] 2015-04-13 06:51
We are also having issues with Yosemite 10.10.3.

None of our js:true feature specs work anymore (all other specs working, and works fine on 10.10.2)

Only interesting thing we have been able to determine thus far,

we have a little wait_for_ajax that uses

  page.evaluate_script('jQuery.active').zero?

JQuery is nil on Yosemite 10.10.3. but not at 10.10.2 all other configuration the same.

**Comment by dboyd68** [comment] 2015-04-13 07:28
Hi Justin808, something to take a look at that we are playing with 

if you turn webkit into webkit_debug.

Noticed that on 10.10.3 we are having issues loading external js files 

Received 0 from "https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" 

Only seems to be an issue if loaded via SSL.

**Comment by styrmis** [comment] 2015-04-13 14:53
I was caught out by this today; switching to protocol agnostic URLs (e.g. `//www.google.com/jsapi` instead of `https://www.google.com/jsapi` has allowed us to bypass this issue for now; thanks @dboyd68!

**Comment by seurdge** [comment] 2015-04-13 15:45
Oh wow thx a lot @styrmis for the workaround you make my day !!! I got downvoted on StackOverflow trying to express this bug being too unclear ;-)

**Comment by jferris** [comment] 2015-04-13 15:55
It seems like this is probably not a bug in capybara-webkit, so I'm going to close this. Please comment again if you think there's something the driver is doing wrong.

Also, it may be worth trying out the `disable_unknown_urls` feature in recent versions, as I believe it will eliminate issues like this.

**Closed by jferris** 2015-04-13 15:55 UTC
