### ISSUE TITLE
click_button doesn't appear to click the right location when browser executing asynchronous javascript

### ISSUE THREAD

**Issue by rosskevin** [thoughtbot/capybara-webkit#714] opened 2015-01-27 02:03 UTC
Stay with me, I've spent a great deal of time debugging.  I've narrowed it down to a location in a test where if I put a one second sleep before the button press, all is well.  When the sleep is gone, the cursor is in the wrong location (as shown in the screenshot) and none of the javascript handlers are fired off.

Now, a one second sleep in one test isn't too big of a deal, but we have several tests having this problem.  The `button_click` is simply lost.  What is worse, is that it has been really difficult to reliably get these tests to work, sometimes it is no wait, sometimes it is 1 second, sometimes it fails at 3 seconds.

You might be wanting to say that I "shouldn't use sleep" and I should use the cucumber equivalent of `I should see` so capybara will automatically wait right?  No problem, I have done that and indeed `I should see` the button text is true, and in any case `click_button` is run and succeeds because it isn't invisible, and it is not disabled (visually a disabled button would be distinctive).

The ajax calls in the browser are remote validation related, so I added in some javascript to make sure those completed (they still emit events after completion).   Normally, I would be prone to call this a javascript or form validation problem, but then wouldn't the cursor still render over the button and not off to the side?

So this is my understanding:
**Given** the browser is busy with asynchronous remote javascript calls
**When** I immediately `click_button` on a visible element
**Then** _nothing happens (no js click handlers, no errors)_
**And** the cursor is not in the correct location

![screenshot-failed](https://cloud.githubusercontent.com/assets/136564/5912151/ee9d76fa-a594-11e4-8800-630cee91021a.png)

[This is a dropbox folder with the success and failure logs](https://www.dropbox.com/sh/qcy2pbjih889b06/AADfxB8sDPLepGuUd8V9BxVva?dl=0).
- In the webkit_debug logs, search for `Received "Execute( AfCore.Form.isValidAll() )"`.  This is the location where right before the call to `click_button`, I execute a script to make sure all asynchronous calls are completed.
- The js console logs are quite a bit more concise.   You can see that the `success-js-log-snip.txt` demonstrates that the `[debug][InvitationForm] onSubmitClick` is called, whereas the `failed-js-log-snip.txt` never gets there.

I'm not sure what else to try.  If there is a method I can preemptively call to make sure in special cases that the browser is prepared for the `click_button`, otherwise I'd like it if the code could verify somehow that it clicked the right location.

I'm totally open to suggestions.  What is clear is that it took two days to get down to this, and I still cannot reliably get tests to run with a specific sleep time (which is undesirable to begin with).

**Comment by rosskevin** [comment] 2015-01-27 02:04
As another quick note, I have the same issue on a non-modal page as well.

**Comment by mhoran** [comment] 2015-01-27 02:09
My first guess would be CSS animations. In my current app, we've disabled these in test mode with the following in our application layout:

```haml
-# This disables modal animations/transitions in tests.
- if Rails.env.test?
  :css
    .modal.fade .modal-dialog { 
      transition: inherit;
      -webkit-transition: inherit;
    }
```

Of course, this only resolves the issue for modals with CSS transitions. If you're displaying other content with transitions, you'll have to adjust the CSS as necessary.

**Comment by rosskevin** [comment] 2015-01-27 02:15
Thanks @mhoran, I just tried without success.  I should note that my cucumber/capybara test is doing some `fill_in` behaviors on the form prior to the `click_button` and they are successful.  Also note that this happens on a normal page.  With that said, I'll leave in your suggestion and take a look at more of the bootstrap default transitions to try and avoid future issues.

The cursor should render on the button correct?

**Comment by rosskevin** [comment] 2015-01-27 17:05
**Workaround:**

While I hate to workaround this, I don't know another way.  The best thing I could think of is adding to the javascript event queue to ensure that the click was after other javascript had run.  This is a two part workaround:

**Part 1:** make sure that all buttons have an id attribute
Since I'm including jquery.ui, I used their handy method `uniqueId()`.  This also presupposes that you are sticking the `Rails.env` on the `body` as `data-env`.

```coffeescript
$ ->
  env = $('body').data('env')
  isTest = 'test' is env

  return unless isTest

  # give any submit or button an id, so that we can trigger click on a button.
  $('input[type="submit"], button').uniqueId()
```

**Part 2:** change the cucumber form_steps `I press`

```ruby
When /^I press "([^"]*)"$/ do |field|
  if webkit?
    button = find(:button, field, {})
    page.find("##{button[:id]}").trigger(:click)
  else
    click_button(field)
  end
end
```

where the `webkit?` method is

```ruby
def webkit?
  [:webkit, :webkit_debug].include? Capybara.current_driver
end
```

This is just a workaround.  I still think this should just work, but I'm not sure how to help any further at this point.

**Comment by calleerlandsson** [comment] 2015-06-12 12:32
@rosskevin Is there any element overlapping the button that might confuse the native clicking functionality in capybara-webkit?

**Comment by rosskevin** [comment] 2015-06-12 16:53
@calleerlandsson I do not believe so, because this occurs on modal and non-modal/standard pages.  I haven't revisited this for months and have updated libraries, but my workaround is still in place and working.  As I mentioned, if `I can see` the text on the button, it should be visible, and I think the issue is most exemplified by the location of the cursor.  Consistently every time I saw this error, the cursor did not make it over the button.

**Comment by calleerlandsson** [comment] 2015-06-15 07:42
@rosskevin Have you tried running the spec without the workaround using the latest version of capybara-webkit?

@mhoran, @jferris Is there something more we could try here?

**Comment by mhoran** [comment] 2015-06-16 01:59
It'd be great if we could get an isolated reproduction of the issue. It's possible that there's some platform specific or dependency specific combination that's causing the issue. Without being able to debug locally, it's extremely difficult to come up with a solution.

I've seen some weirdness with CSS3 transitions which exhibited this behavior, but it seems that disabling those didn't solve this issue.

It could also be that the modal opening is triggering some sort of reflow, which invalidates the pointer position that we calculate.

**Comment by jferris** [comment] 2015-06-16 15:14
I guess there could be a race condition in our click handling, assuming that it's possible for the page to change while we're processing a click. A lost race would look like this:

* Thread 1: Find the element.
* Thread 1: Calculate the click position for that element.
* Thread 1: Perform a hit test to validate that position.
* Thread 2: Move the element in some way (JavaScript, CSS transition, etc)
* Thread 1: Send a click at the calculated position.

Since the hit test passed, we wouldn't raise an exception, so Capybara won't retry the click.

If this is the issue, it will be very difficult to reproduce in a unit test.

@rosskevin in your application, does this fail consistently or erratically?

**Comment by rosskevin** [comment] 2015-06-16 15:29
@jferris  This _was_ consistently a failure (I need to reaffirm as requested).  As @mhoran suggested, I removed transitions/animations in the test environment.  As shown in the screenshot, the cursor is over a position where the button never was (even with the default transitions enabled).  So I don't believe `Thread 2: Move` is occurring in this case.  I should mention that buttons are present and visible but initially disabled.  This definitely only appears as javascript is running validations and buttons are disabled/enabled.

@calleerlandsson our CI build is currently broken, it will be a couple of days before our dev is back to passing, when it is, I'll pull the workaround to see if it still breaks on the same tests.

@mhoran - regarding modal/reflow, I'm guessing this is a broader issue, as I was reproducing it on non-modals.  Nonetheless, some kind of dynamic nature could be occurring on that page, but certainly the validation and button enablement is common amongst the cases I have seen.

Please give me a couple of days to get my dev CI back to passing, I'll reaffirm the issue.

**Comment by twalpole** [comment] 2015-06-16 20:43
@rosskevin When you say you were seeing this error on non-modal pages, did they still have slide out/dropdown panels or anything like that?  Since you're using jquery.ui  you should able to disable all of its animations by setting jQuery.fx.off to true when testing.

**Comment by rosskevin** [comment] 2015-06-19 19:50
We disable the workaround, same problem.

```
Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-53-generic x86_64)
capybara-webkit (1.5.2)
capybara (2.4.4)
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu
```

We also turned off jQuery.fx just to be sure (it's not involved but is present), and it made no difference.

**Comment by rosskevin** [comment] 2015-06-19 20:14
Something changed, pointer location is different:

![modal-diff-pointer-location](https://cloud.githubusercontent.com/assets/136564/8262155/d58f7f38-1695-11e5-820e-29a2f2b21f2b.png)

Here's an example from a non-modal:

![non-modal](https://cloud.githubusercontent.com/assets/136564/8262165/e7938d14-1695-11e5-9457-f2d4cf43819b.png)

The click is simply lost, it appears.

**Comment by twalpole** [comment] 2015-06-19 20:39
@rosekevin -- so now that animations are disabled the cursor is showing over the correct button?  If that is the case, are your JS click handlers attached before or after the box is shown?  If after it's possible the click is happening before the handlers are in place.

**Comment by rosskevin** [comment] 2015-06-19 20:49
1.  CSS Animations were disabled previously.  
2.  Tried removing the workaround - failure
3.  Tried adding the jquery fx disablement - failure - no change.

This isn't animated, and it isn't a jquery.ui component.  Bootstrap button.  I don't think animation is playing a role at this point (though I will never say never).

I think handlers are attached, but the button is disabled initially until form is valid (using [formvalidation.io](https://github.com/formvalidation/formvalidation.io)).  Click race could be the issue, the JS is busy doing a remote ajax validation in both cases.  That is why I introduced `page.find("##{button[:id]}").trigger(:click)`, to get the click on the JS thread to be sure it is processed, probably after enablement is completed.

This doesn't really explain the cursor position on the modal though.

**Comment by twalpole** [comment] 2015-06-19 21:57
So bootstrap modal does its on animation using css transitions if available -- you can be sure they're fully turned it off by removing the "fade" class from the modal.  Since the image is now showing correctly though, the issue very well could be that you're clicking on the button while its still disabled.  You could try

    page.find("##{button[:id]}:not([disabled])").click()

which will wait until the button enables (assuming it is disabled with the disabled attribute) before clicking it

**Comment by rosskevin** [comment] 2015-06-22 15:17
@twalpole - tried `page.find("##{button[:id]}:not([disabled])").click()`, it didn't work.  It yields the same result.

**Comment by mfrejnik** [comment] 2016-08-12 08:37
Is there anything going on with this issue ? I have similar issue with my test.

**Comment by mhoran** [comment] 2016-08-13 00:18
@mfrejnik the developers of capybara-webkit have been unable to reproduce this issue in isolation, making it extremely difficult to develop a fix. If you can extract a simple test case that reliably reproduces the issue, that will go a long way in helping to develop a fix.

**Comment by twalpole** [comment] 2017-10-18 19:21
Closing due to age and the lack of a way to replicate -- We can reopen when a way to replicate with current releases is provided.

**Closed by twalpole** 2017-10-18 19:21 UTC

**Comment by NuclearMachine** [comment] 2020-02-29 23:09
@twalpole This is still present fyi. 3 years later. 

Heres a tip if you cant reproduce, do not `rspec` over a single file. Because for some reason, the bug will not appear. Instead have several mock specs ready and do `rspec`  from the app folder. 
 (instead of `rspec/target_file.rb`

**Comment by twalpole** [comment] 2020-03-01 01:03
@NuclearMachine this gem went end-of-life quite some time ago. The testing world has moved on

**Comment by NuclearMachine** [comment] 2020-03-01 05:38
@twalpole . Oh no. That comment is meant for the Ruby on Rails version. Aka https://github.com/teamcapybara/capybara/issues/1890.
