### ISSUE TITLE
JQuery UI 'Combobox' not supported

### ISSUE THREAD

**Issue by lunks** [thoughtbot/capybara-webkit#98] opened 2011-07-04 22:16 UTC
Using this example code: http://jqueryui.com/demos/autocomplete/#combobox

And this capybara helper:

```ruby
  def autocomplete(locator, options = {})
    scope = "//label[text()='#{locator}']/parent::div"
    within :xpath, scope do
      text_input = find(:xpath, "input")
      text_input.set options[:with]
    end
    within 'li.ui-menu-item' do
      find('a').click
    end
  end
```
This raises an error stating it 'can't find an li.ui-menu-item'. This works on Webdriver.

You can use autocomplete as you would use capybara's fill_in.

**Comment by calleerlandsson** [comment] 2015-05-29 09:11
Can someone confirm if this is still an issue in the latest version of capybara-webkit?

Could this be related or a duplicate of #50?

**Comment by calleerlandsson** [comment] 2015-06-05 09:14
I'll close this issue due to inactivity. Please re-open it if you're still experiencing these issues.

**Closed by calleerlandsson** 2015-06-05 09:14 UTC
