### ISSUE TITLE
Consecutive tests fail with Capybara::Webkit::CrashError: Broken pipe

### ISSUE THREAD

**Issue by rpazyaquian** [thoughtbot/capybara-webkit#965] opened 2016-11-09 19:09 UTC
I'm using `capybara-webkit` with `qt5` and `jruby-9.1.5.0`, and I'm trying to get my tests to run consecutively, rather than in parallel. Unfortunately, it looks like webkit crashes after the first test that's run, and none of the issues so far have resembled my problem. Upgrading Qt to 5 didn't resolve the issue, and the error message+debug output isn't offering any insight on what's happening.

My setup:

```
Capybara: 2.4.4
capybara-webkit: 1.11.1
Qt: 5.3.2
WebKit: 538.1
QtWebKit: 5.3.2
```

Here's an example output of the tests:

```
Received "FindXpath(/html/body/*)"
Started "FindXpath(/html/body/*)"
Finished "FindXpath(/html/body/*)" with response "Success()"
Wrote response true ""
      shows number of people that are out of office
    when no one is out of office
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "AllowUrl(http://www.google.com/jsapi)"
Started "AllowUrl(http://www.google.com/jsapi)"
Finished "AllowUrl(http://www.google.com/jsapi)" with response "Success()"
Wrote response true ""
Received "AllowUrl(www.google-analytics.com)"
Started "AllowUrl(www.google-analytics.com)"
Finished "AllowUrl(www.google-analytics.com)" with response "Success()"
Wrote response true ""
Received "FindXpath(/html/body/*)"
Started "FindXpath(/html/body/*)"
Finished "FindXpath(/html/body/*)" with response "Success()"
Wrote response true ""
      gang-all-here tile preview (FAILED - 1)
  tile actions
    when member
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "AllowUrl(http://www.google.com/jsapi)"
Started "AllowUrl(http://www.google.com/jsapi)"
Finished "AllowUrl(http://www.google.com/jsapi)" with response "Success()"
Wrote response true ""
Received "AllowUrl(www.google-analytics.com)"
Started "AllowUrl(www.google-analytics.com)"
Finished "AllowUrl(www.google-analytics.com)" with response "Success()"
Wrote response true ""
Received "FindXpath(/html/body/*)"
Started "FindXpath(/html/body/*)"
Finished "FindXpath(/html/body/*)" with response "Success()"
Wrote response true ""
      adding OOO entry (FAILED - 2)
      existing OOO entry
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "AllowUrl(http://www.google.com/jsapi)"
Started "AllowUrl(http://www.google.com/jsapi)"
Finished "AllowUrl(http://www.google.com/jsapi)" with response "Success()"
Wrote response true ""
Received "AllowUrl(www.google-analytics.com)"
Started "AllowUrl(www.google-analytics.com)"
Finished "AllowUrl(www.google-analytics.com)" with response "Success()"
Wrote response true ""
Received "FindXpath(/html/body/*)"
Started "FindXpath(/html/body/*)"
Finished "FindXpath(/html/body/*)" with response "Success()"
Wrote response true ""
        editing (FAILED - 3)
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "AllowUrl(http://www.google.com/jsapi)"
Started "AllowUrl(http://www.google.com/jsapi)"
Finished "AllowUrl(http://www.google.com/jsapi)" with response "Success()"
Wrote response true ""
Received "AllowUrl(www.google-analytics.com)"
Started "AllowUrl(www.google-analytics.com)"
Finished "AllowUrl(www.google-analytics.com)" with response "Success()"
Wrote response true ""
Received "FindXpath(/html/body/*)"
Started "FindXpath(/html/body/*)"
Finished "FindXpath(/html/body/*)" with response "Success()"
Wrote response true ""
        deleting (FAILED - 4)
      other stuff
        prev-next buttons (PENDING: Temporarily disabled with xscenario)
Finished "EnableLogging()" with response "Success()"
Wrote response true ""
Received "SetTimeout(-1)"
Started "SetTimeout(-1)"
Finished "SetTimeout(-1)" with response "Success()"
Wrote response true ""
Received "AllowUrl(http://www.google.com/jsapi)"
Started "AllowUrl(http://www.google.com/jsapi)"
Finished "AllowUrl(http://www.google.com/jsapi)" with response "Success()"
Wrote response true ""
Received "AllowUrl(www.google-analytics.com)"
Started "AllowUrl(www.google-analytics.com)"
Finished "AllowUrl(www.google-analytics.com)" with response "Success()"
Wrote response true ""
Received "FindXpath(/html/body/*)"
Started "FindXpath(/html/body/*)"
Finished "FindXpath(/html/body/*)" with response "Success()"
Wrote response true ""
        changing months (FAILED - 5)

<snip>

Failures:

  1) Out of office dashboard preview when no one is out of office gang-all-here tile preview
     Failure/Error: visit new_session_path
     Capybara::Webkit::CrashError:
       The webkit_server process crashed!

         Broken pipe - No message available

       This is a bug in capybara-webkit. For help with this crash, please visit:

       https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
     # /usr/local/bundle/gems/capybara-webkit-1.11.1/lib/capybara/webkit/browser.rb:218:in `command'
     # /usr/local/bundle/gems/capybara-webkit-1.11.1/lib/capybara/webkit/browser.rb:19:in `visit'
     # /usr/local/bundle/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:50:in `visit'
     # /usr/local/bundle/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
     # /usr/local/bundle/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block in DSL'
     # ./spec/features/out_of_office_spec.rb:16:in `block in (root)'
     # ./spec/support/headless.rb:4:in `block in (root)'
     # /usr/local/bundle/gems/headless-2.3.1/lib/headless.rb:143:in `run'
     # ./spec/support/headless.rb:3:in `block in (root)'

  2) Out of office tile actions when member adding OOO entry
     Failure/Error: visit new_session_path
     Capybara::Webkit::CrashError:
       The webkit_server process crashed!

         Broken pipe - No message available

       This is a bug in capybara-webkit. For help with this crash, please visit:

       https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
     # /usr/local/bundle/gems/capybara-webkit-1.11.1/lib/capybara/webkit/browser.rb:218:in `command'
     # /usr/local/bundle/gems/capybara-webkit-1.11.1/lib/capybara/webkit/browser.rb:19:in `visit'
     # /usr/local/bundle/gems/capybara-webkit-1.11.1/lib/capybara/webkit/driver.rb:50:in `visit'
     # /usr/local/bundle/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
     # /usr/local/bundle/gems/capybara-2.4.4/lib/capybara/dsl.rb:51:in `block in DSL'
     # ./spec/features/out_of_office_spec.rb:16:in `block in (root)'
     # ./spec/support/headless.rb:4:in `block in (root)'
     # /usr/local/bundle/gems/headless-2.3.1/lib/headless.rb:143:in `run'
     # ./spec/support/headless.rb:3:in `block in (root)'

<repeat exception for every other failing test>

Finished in 16.24 seconds (files took 16.16 seconds to load)
10 examples, 5 failures, 4 pending
```

I was hoping to figure out why this was happening based on the stack trace, but I'm not sure I have the chops to figure that out. Any idea why this might be happening?

Let me know if you need more information about my platform or anything.

**Comment by jferris** [comment] 2016-11-10 15:43
Does it pass without crashing if you run only one spec? Does it matter which spec you run? If it works once and then crashes no matter what, it seems likely that it's crashing somewhere when trying to reset the driver. This is one of the trickier parts of the driver, because everything is asynchronous and needs to be synced up and then deallocated.

One thing that's suspicious is that I don't see any `Reset` commands in your log. Usually, a reset command is sent after each spec. This should happen just before the options are reset, so it should be before `Finished command EnableLogging`.

Are you able to share anything from your RSpec setup, like your `spec_helper.rb` or `rails_helper.rb`? Anything related to database setup (DatabaseCleaner, etc) might be helpful as well.

**Comment by rpazyaquian** [comment] 2016-11-10 21:08
Here's our `spec_helper`:

```
```

**Comment by rpazyaquian** [comment] 2016-11-10 21:20
Running a single spec works fine, and the spec that's run doesn't seem to matter.

Here's our `spec_helper`:

```
require 'simplecov'
SimpleCov.start

require 'capybara/rspec'
require 'capybara-webkit'
require 'rack_session_access/capybara'

Capybara.javascript_driver = :webkit_debug

Capybara::Webkit.configure do |config|
  config.allow_url("http://www.google.com/jsapi")
  config.allow_url("www.google-analytics.com")
end

RSpec.configure do |config|

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.run_all_when_everything_filtered = true
  config.filter_run_excluding :type => :request

  config.disable_monkey_patching!
  if config.files_to_run.one?
    config.default_formatter = 'doc'
  end
  config.order = :random
 Kernel.srand config.seed
end
```

and our `rails_helper`:

```
ENV['RAILS_ENV'] ||= 'test'
require 'spec_helper'
require File.expand_path('../../config/environment', __FILE__)
require 'rspec/rails'

Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }

RSpec.configure do |config|
  config.use_transactional_fixtures = false
  config.infer_spec_type_from_file_location!

  config.include Capybara::DSL
end
```

**Comment by twalpole** [comment] 2016-11-10 21:26
You don't appear to be requiring capybara/rspec anywhere - so you don't have the session being reset between each test - https://github.com/jnicklas/capybara/blob/master/lib/capybara/rspec.rb#L19  . That's why you're not seeing reset commands between each spec, not sure if that's whats causing the crashes though.

**Comment by rpazyaquian** [comment] 2016-11-10 21:27
It's on line 4 of `spec_helper`:

```
require 'simplecov'
SimpleCov.start

require 'capybara/rspec'
require 'capybara-webkit'
require 'rack_session_access/capybara'
<etc>
```

Should it be required elsewhere as well?

**Comment by twalpole** [comment] 2016-11-10 21:34
@rpazyaquian Sorry I noticed it as soon as I had posted (not sure how I missed it before) - I immediately thereafter deleted my comment

**Comment by rpazyaquian** [comment] 2016-11-10 21:35
No problem!

**Comment by twalpole** [comment] 2016-11-10 21:43
@rpazyaquian Have you tried updating Capybara ?  capybara-webkit supports up to 2.7.1  - the versions you're using (2.4.4) is pretty old.

**Comment by rpazyaquian** [comment] 2016-11-10 22:09
I upgraded to Capybara 2.7.1, but it looks like consecutive specs are still failing with the same message. :( Still not seeing any `Reset()`s after finishing the first spec...although, I _did_ run into an `ArrayOutOfBoundsException` related to JRuby threading or whatever. Could that be a clue?

**Comment by twalpole** [comment] 2016-11-11 00:07
No idea about the ArrayOutOfBoundsException, or why you're not having resets occur -- do you have any other RSpec after hooks?

**Comment by rpazyaquian** [comment] 2016-11-11 15:21
Not that I know of.

Let me speak a little more of our setup. We're running in a Vagrant-Docker setup, using JRuby and docker-compose. I don't know if that environment could possibly cause any issues, but it's more information that may help. We're currently using JRuby 9.1.5.0, and I don't know if that would affect anything.

What code determines whether a `Reset()` should occur? We do have this line in `rails_helper`, and I'm wondering if it's possibly causing this:

```
  # If you're not using ActiveRecord, or you'd prefer not to run each of your
  # examples within a transaction, remove the following line or assign false
  # instead of true.
  #config.use_transactional_fixtures = true
  config.use_transactional_fixtures = false
```

although I tried changing it to `true` and the errors continued, so maybe that's not the case.

**Comment by jferris** [comment] 2016-11-14 14:14
Out of curiosity: if you add `page.reset!` at the end of a few `it` blocks and then run them consecutively, do they still fail the same way? Do you see `Reset` calls coming into the debug log?

**Comment by rpazyaquian** [comment] 2016-11-14 17:36
@jferris, it looks like they continue to fail and no extra `Reset()` calls come in. Here's how the spec looks:

```
  describe "dashboard preview" do
    context "when no one is out of office" do
      it "gang-all-here tile preview" do
        ooo_preview = page.find("#ooo")
        expect(ooo_preview).to have_selector("div.all-here")
        page.reset!
      end
    end

    context "when someone is out of office" do
      before(:each) do
        FactoryGirl.create(:event, :now, board_id: board.id, person_id: admin.id)
        go_to_board(board.id)
      end

      it "shows number of people that are out of office", js: true do
        ooo_preview = page.find("#ooo")
        expect(ooo_preview).to have_selector("div.overview-main-content")
        within ooo_preview do
          ooos = find("ul").all("li")
          expect(ooos.count).to eq board.out_today.count
        end
        page.reset!
      end
    end
  end
```

The only instances of `Reset()` are in this snippet, occurring prior to the first block passing:

```
<...>
Received "Reset()"
Started "Reset()"
Finished "Reset()" with response "Success()"
Wrote response true ""
<...>
```

**Comment by twalpole** [comment] 2016-11-14 18:05
@rpazyaquian This doesn't help at all with your failures but when testing counts your tests will be more robust if you pass them in as options to Capybaras matchers rather than testing them separately since it allows Capybaras waiting/retrying behavior to work when pages are loading dynamically etc.   In your test case - something like

    it "shows number of people that are out of office", js: true do
        ooo_preview = page.find("#ooo")
        expect(ooo_preview).to have_css("div.overview-main-content")
        expect(ooo_preview).to have_css('ul li', count: board.out_today.count)
      end

**Comment by rpazyaquian** [comment] 2016-11-15 18:47
@twalpole Good to know, I will keep that in mind for future tests - I may have been relying on outdated information and cheat sheets.

Any more insights on why the page is not being reset? I can try writing and running simpler specs as a way to triangulate the core problem, if that helps.

**Comment by twalpole** [comment] 2016-11-15 18:57
@rpazyaquian When you require capybara/rspec it adds an after hook that should call reset_sessions! between every test - If you can step through code and figure out whether that is getting called or why it's not that would narrow this down.  Or if you can produce a small example that produces the same behavior we can look at.

**Comment by rjdegelder** [comment] 2017-03-28 08:51
Any updates on this? I'm getting the same errors running consecutive specs.

- ruby 2.3
- capybara 2.13.0
- capybara-webkit 1.14.0
- qt 5.3.2

**Comment by emerson-h** [comment] 2017-04-20 16:14
I have the same problem with the following setup:
- OSX 10.11.6 (El Capitan)
- Ruby 2.2
- capybara 2.13.0
- capybara-webkit 1.14.0
- qt 5.5.1

**Comment by twalpole** [comment] 2017-04-20 16:54
@emerson-h Without an example that reproduces this error, it's basically impossible to debug - can you provide one?

**Comment by emerson-h** [comment] 2017-04-20 16:59
@twalpole I'll try to pull together a minimum reproduction repo later this afternoon and will post a link here.

**Comment by lewaabahmad** [comment] 2017-05-25 21:14
@emerson-h How'd that repo go? Also getting a similar issue on my end. To be more clear, errors include: 
`
EOFError:
            end of file reached
          # <internal:prelude>:78:in `__read_nonblock'
          # <internal:prelude>:78:in `read_nonblock'
          # ./spec/support/helpers/features/donations/create/helpers.rb:37:in `when_customer_enters_credit_card_on_payment_page'
          # ./spec/features/donations/create/payment/error_spec.rb:21:in `block (2 levels) in <top (required)>'
`
and 
` 
raise(Capybara::Webkit::CrashError, <<-MESSAGE.strip)
            The webkit_server process crashed!

              #{exception.message}

            This is a bug in capybara-webkit. For help with this crash, please visit:

            https://github.com/thoughtbot/capybara-webkit/wiki/Reporting-Crashes
                  MESSAGE

          Capybara::Webkit::CrashError:
            The webkit_server process crashed!

              Broken pipe
`

Also, seeing warnings about blocking/allowing urls. This is despite the following rails_helper config: 
`
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
abort("The Rails environment is running in production mode!") if Rails.env.production?

require 'spec_helper'
require 'rspec/rails'
require 'capybara/rails'
require 'capybara/webkit'

ActiveRecord::Migration.maintain_test_schema!

RSpec.configure do |config|

  config.infer_spec_type_from_file_location!

  config.filter_rails_from_backtrace!

  config.include FactoryGirl::Syntax::Methods
end

Capybara.javascript_driver = :webkit

Capybara.configure do |config|

  config.default_max_wait_time = 10 # seconds
  config.default_driver        = :webkit
end

Capybara::Webkit.configure do |config|
  
  config.allow_url("js.stripe.com")
  
  config.skip_image_loading
  config.block_unknown_urls
end

`
Copied all of it to show that I'm not loading a different driver. Here's my spec_helper preemptively:
`
require 'capybara/rspec'
require 'factory_girl_rails'

Dir[File.dirname(__FILE__) + "/support/**/*.rb"].each { |f| require f }

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  # STDOUT configs
  config.color = true
  config.formatter = :documentation
end
`

**Comment by jtrees** [comment] 2017-08-01 08:30
We also get this issue but it doesn't occur on our development machines (MacBooks). It only crops up on our continuous testing runners - seemingly at random.

* Linux 4.4.0-83-generic #106-Ubuntu Server 16.04 LTS
* ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
* capybara 2.13.0
* capybara-webkit 1.14.0
* Qt 5.5.1

@emerson-h Did you make any progress with that minimum reproduction repo?

**Comment by twalpole** [comment] 2017-11-09 01:54
Closing due to lack of ability to reproduce,  we can reopen if someone provides a way to reproduce this.

**Closed by twalpole** 2017-11-09 01:54 UTC
