### ISSUE TITLE
Installing Qt and compiling capybara webkit for Ubuntu 16.04

### ISSUE THREAD

**Issue by ehannes** [thoughtbot/capybara-webkit#924] opened 2016-06-07 08:41 UTC
Time to update the wiki page for [Installing Qt and compiling capybara webkit](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit). Ubuntu 16.04 is missing. Ubuntu 14.04 is included, but that's two years old now.

Additionally, there's a note below the instructions for Ubuntu 14.04: `You should use qt4, using qt5 will fail`. I get this warning when I run Capybara webkit now: `WARNING: The next major version of capybara-webkit will require at least version 5.0 of Qt.`

**Comment by jferris** [comment] 2016-06-07 13:42
The Wiki page is maintained by the community, as the maintainers can't test compilation on every version of every system. We chose to make the page world-editable so that it would be fast and easy for people to contribute. Unfortunately, that has resulted in numerous incorrect changes, most often the suggestion to use Qt 4. You should use at least Qt 5.0, as the Qt 4 series uses a very old version of WebKit with numerous serious bugs and no support for modern HTML5 features.

I updated the wiki to remove all references to instructions that install Qt 4.

If you do get it compiling using Qt 5 on Ubuntu 16.04, I'd appreciate it if you could update the wiki page with the steps you used.

I'm going to close this issue as it's not a bug in capybara-webkit, but feel free to ask questions and continue commenting.

**Closed by jferris** 2016-06-07 13:42 UTC

**Comment by ToadJamb** [comment] 2017-02-16 07:21
I have updated the wiki with packages that appear to have done the trick for me on Ubuntu Xenial (16.04). Just stating it here in case others run across this in search of an answer.

Here's the link: https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#ubuntu-xenial-1604
