### ISSUE TITLE
Capybara README remark clarification

### ISSUE THREAD

**Issue by mcfilib** [thoughtbot/capybara-webkit#1074] opened 2018-09-21 09:05 UTC
From the [Capybara README](https://github.com/teamcapybara/capybara#capybara-webkit)

> Note: capybara-webkit depends on QtWebkit which went EOL quite some time ago. There has been an attempt to revive the project but capybara-webkit is not yet (AFAIK) compatible with the revived version of QtWebKit (could be a good OSS project for someone) and as such is still limited to an old version of QtWebKit. This means its support for modern JS and CSS is severely limited. 

Is someone able to comment on the status of `capybara-webkit` based on what's written above? Is this still true? Is it likely to change?

**Comment by jferris** [comment] 2018-09-27 15:38
I haven't had a chance to look into what QtWebKit is up to lately, but as far as I know, this is still true.

Qt replaced QtWebKit with QtWebEngine, which is not backwards compatible (it would mean rewriting parts of capybara-webkit) and it doesn't support everything we use. Using that would basically mean making a capybara-webengine project instead, and nobody has undertaken that effort.

There was [some effort](https://github.com/mhoran/capybara-chromium) to use CEF as an alternate backend for Capybara, but it was abandoned.

If anybody has results from trying to build against the revived QtWebKit project, I'd love to hear about them.

This all basically means that capybara-webkit uses an old version of WebKit, so it's not a good choice for testing a fancy JavaScript WYSIWYG editor, but it continues to work well for testing basic JavaScript functionality in Rails applications.

I'm closing this issue, as it's not a bug in capybara-webkit, but feel free to continue the conversation.

**Closed** 2018-10-04 15:29 UTC
