### ISSUE TITLE
AngularJS sites render against QT 4 but not QT 5 on Mac

### ISSUE THREAD

**Issue by spilth** [thoughtbot/capybara-webkit#750] opened 2015-04-06 21:48 UTC
We're having a problem where AngularJS sites don't seem to render correctly when using capybara-webkit and QT 5. It works fine using QT 4 though.

Note: the site below is not our site. It's just some AngularJS-powered site I pulled from https://builtwith.angularjs.org/

We're using:
- Homebrew 0.9.5
- OS X 10.9.5

Below are the steps to reproduce the issue.
## Install Ruby 2.2.0

```
$ rvm install 2.2.0
$ rvm use 2.2.0
$ rvm gemset use capybara-bug --create
```
## Install Necessary Gems

```
$ gem install capybara
$ gem install launchy
```
## Remove All Versions of QT

```
$ brew uninstall qt
$ brew uninstall qt5
```
## Run against QT 4

```
$ brew install qt
$ gem install capybara-webkit
$ irb

require 'capybara'
require 'capybara-webkit'
include Capybara::DSL
Capybara.current_driver = :webkit
Capybara.javascript_driver = :webkit
visit "http://sbb.cellfinder.org/"
save_and_open_screenshot
exit
```

You can see a complete screenshot of the web site.
## Run against QT 5

```
$ brew uninstall qt
$ brew install qt5
$ brew link qt5 --force
$ gem install capybara-webkit
$ irb

require 'capybara'
require 'capybara-webkit'
include Capybara::DSL
Capybara.current_driver = :webkit
Capybara.javascript_driver = :webkit
visit "http://sbb.cellfinder.org/"
save_and_open_screenshot
exit
```

You can see an incomplete screenshot of the web site.

**Comment by jferris** [comment] 2015-04-09 21:07
I've confirmed this on Linux with Qt 5, but I don't have any idea why it's not rendering yet.

```
Capybara: 2.4.4
capybara-webkit: 1.4.1
Qt: 5.4.0
WebKit: 538.1
QtWebKit: 5.4.0
```

**Comment by twalpole** [comment] 2017-10-18 19:17
Closing due to age, we can reopen if this is still an issue with current releases

**Closed by twalpole** 2017-10-18 19:17 UTC
