### ISSUE TITLE
Entity bodies are not passed back for PATCH requests

### ISSUE THREAD

**Issue by thoughtless** [thoughtbot/capybara-webkit#553] opened 2013-07-25 23:23 UTC
Our app passes data in the entity body of a PATCH request via jquery. It works fine in the browser but when capybara-webkit makes the request the (rails) server never gets the entity body.

The problem is similar to https://github.com/thoughtbot/capybara-webkit/issues/427

Is this also not supported by QtWebKit?

**Comment by hiattp** [comment] 2015-03-19 10:16
@Borzik looks like qt 5.4 fixed this, does updating qt work for you?

**Comment by hiattp** [comment] 2015-03-20 00:52
According to [QTBUG-42456](https://bugreports.qt.io/browse/QTBUG-42456) the Qt side of this issue was fixed in 5.4.1. But after updating Qt:

```sh
% qmake -v
QMake version 3.0
Using Qt version 5.4.1 in /usr/local/Cellar/qt5/5.4.1/lib
```

Webkit still doesn't work with PATCH requests. Interestingly, 5.4.1 will send `CONTENT_LENGTH` with a value that looks correct, but not `CONTENT_TYPE` or the body. Haven't delved in yet but maybe the ball is back in Webkit's court; @jferris thoughts?

**Comment by hiattp** [comment] 2015-03-20 02:49
As a quick followup and for anyone else hunting down a solution, [poltergeist](https://github.com/teampoltergeist/poltergeist) running PhantomJS 2 (which uses Qt 5) handles PATCH requests as expected.

**Comment by jferris** [comment] 2015-03-27 16:00
It looks like we directly send the outgoing data upstream to Qt: https://github.com/thoughtbot/capybara-webkit/blob/master/src/NetworkAccessManager.cpp#L16

I'm not sure what we would be doing differently.

@hiattp did you make sure to rebuild capybara-webkit after updating Qt?

**Comment by hiattp** [comment] 2015-03-28 01:13
I uninstalled and reinstalled the gem after upgrading Qt, would there be another step to rebuilding? I did notice a different request structure (e.g. the headers noted above) and slightly different test errors after reinstalling so I felt confidant it was using the new version of Qt but maybe I missed a step

**Comment by jferris** [comment] 2015-04-09 17:32
@hiattp nope, uninstalling and reinstalling should do it.

I'll try to take a look at this soon.

**Comment by jferris** [comment] 2015-04-09 20:50
@hiattp I just tried to reproduce this, but I'm unable to write a failing test: https://github.com/thoughtbot/capybara-webkit/commit/6b6a2e10d34ce96223dd87ed65221017798e474e

If you have some time, could you try running that test locally? It's on the `jf-patch-body-test` branch.

**Comment by hiattp** [comment] 2015-05-26 03:12
@jferris Sorry for the long delay; I couldn't make that test fail either. And yet switching from poltergeist to webkit still makes patch requests fail in my Rails suites (no bodies being sent). Very mysterious; I'll try to dig deeper.

**Comment by philipp-spiess** [comment] 2015-07-15 12:10
I had the same problem when running with `qt4`. Updating to `qt5` solved the issue for me.

I'm now on `5.4.1` and installed it using `homebrew` for OSX:

```shell
brew remove qt
brew install qt5
brew linkapps qt5
brew link --force qt5

gem uninstall capybara-webkit
bin/bundle install
```

I'm now waiting to have the qt5 apt packages approved by [Travis CI](travis-ci.com): https://github.com/travis-ci/travis-ci/issues/4352

**Comment by tcoopman** [comment] 2015-10-02 13:35
I have the same issue and I tried to make it work with Qt5.5 but patch requests still fail. (This is on ubuntu 14.04)

**Comment by dkniffin** [comment] 2015-10-26 15:37
I'm having the same issue on OS X (Yosemite). I'm running qt5:

````
$ qmake --version
QMake version 3.0
Using Qt version 5.5.0 in /usr/local/Cellar/qt5/5.5.0_1/lib
````

**Comment by voltechs** [comment] 2015-11-05 23:01
Same here, OS X Yosemite run-ing QT5
```$ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/local/Cellar/qt5/5.5.1/lib```

**Comment by tombroomfield** [comment] 2015-11-16 05:43
Same issues, not content body.
```
QMake version 3.0
Using Qt version 5.5.1 in /usr/local/Cellar/qt5/5.5.1/lib`
```

**Comment by delphaber** [comment] 2016-02-10 15:34
+1 

```
↳ $ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/local/Cellar/qt5/5.5.1_2/lib

↳ $ bundle list | grep capybara
  * capybara (2.6.2)
  * capybara-webkit (1.8.0)
```

**Comment by ehannes** [comment] 2016-04-12 05:19
+1, switched to PUT.
```
$ qmake --version
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu

$ bundle list | grep capybara
  * capybara (2.6.2)
  * capybara-webkit (1.10.1)
```

**Comment by wahhaj** [comment] 2016-05-16 13:51
I'm having the same issue - PATCH requests send a correct CONTENT_LENGTH but no CONTENT_TYPE or body. Switching to PUT is not a viable option at the moment.

`$ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/local/Cellar/qt55/5.5.1/lib

$ bundle list | grep capybara
  * capybara (2.7.1)
  * capybara-webkit (1.11.1)
`

**Comment by Didericis** [comment] 2017-02-22 22:45
Same issue on MacOS - Sierra with Qt 5.5.1

```
$ qmake --version
QMake version 3.0
Using Qt version 5.5.1 in /usr/local/Cellar/qt55/5.5.1/lib
```
```
$ system_profiler SPSoftwareDataType
System Software Overview:
  System Version: OS X 10.11.6 (15G1217)
  Kernel Version: Darwin 15.6.0
```

**Comment by twalpole** [comment] 2017-10-18 19:10
Closing this due to age.  We can reopen if/when a way to replicate is provided using current versions

**Closed by twalpole** 2017-10-18 19:10 UTC
