### ISSUE TITLE
Echo errors into STDOUT/STDERR

### ISSUE THREAD

**Issue by JanStevens** [thoughtbot/capybara-webkit#774] opened 2015-05-07 15:09 UTC
Just wasted another day on capybara-webkit,

# Setup
- Parallel_tests
- Xvfb
- Rails 4.2
- ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
- Bundler version 1.9.4
- QMake version 2.01a (Using Qt version 4.8.6 in /usr/lib/x86_64-linux-gnu)
- Jenkins CI

# Problem
I had a typo in my stylesheet (`application.scss` file) for this reason all the feature/requests specs would fail obviously. What I totally missed on Capybara webkit is that fact that it would die instantly with the old famous:

Notice the typo in the end!
```
@import "font-awesome-sprocketss";
```

```
Broken pipe (Errno::EPIPE)
Errno::EPIPE:
Broken pipe
/var/lib/jenkins/jobs/CI/workspace/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.5.1/lib/capybara/webkit/connection.rb:30:in `write'
/var/lib/jenkins/jobs/CI/workspace/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.5.1/lib/capybara/webkit/connection.rb:30:in `puts'
/var/lib/jenkins/jobs/CI/workspace/vendor/bundle/ruby/2.2.0/gems/capybara-webkit-1.5.1/lib/capybara/webkit/connection.rb:30:in `puts'
```

# Improvements
Please output the sprockets error or the whatever reason the capybara webkit process could not boot/connect to STDOUT/STDERR would save everyone a lot of time! This would also help to see what actually when wrong when booting up the application, instead of seeing `Broken Pipe` errors all over the place.

Ps: possibly I should bug somebody else about this

**Comment by jferris** [comment] 2015-05-07 15:32
When capybara-webkit fails with "Broken pipe," it's because the process outright crashed. We try to return helpful error messages whenever possible, but "broken pipe" means the process just died when we didn't expect it to, so we have no idea what happened. It's usually because we have a `NULL` pointer reference somewhere.

I'm not able to reproduce this locally. If I typo a filename in an scss import, capybara-webkit doesnt' crash, I get an error like this:

```
  An error occurred in an after hook
    ActionView::Template::Error: File to import not found or unreadable: font-awesomes.
```

Can you paste a crash log using the `:webkit_debug` driver?

> Using Qt version 4.8.6

I strongly recommend updating to Qt 5. Qt 4 is using a port of WebKit from several years ago. It's full of bugs we can't do anything about and doesn't support any of the advancements in HTML/JavaScript/CSS from the past few years. We'll be dropping support for Qt 4 in an upcoming release.

**Comment by JanStevens** [comment] 2015-05-07 15:36
Allright, understood (will update to Qt 5)

I had an `application.css` with the following:

```
*= require app
```

Then an app.scss with the following:

```
@import "bootstrap-sprockets";
@import "bootstrap";

@import "font-awesome-sprockets";
@import "font-awesome";

// Compass imports
@import "compass/css3";
@import "compass/utilities/general/min";

// Application imports
@import "components/*";
@import "ng-table/ng-table.min"
```

The last file didnt exist anymore

**Comment by jferris** [comment] 2015-05-07 15:48
It sounds like maybe you have your application configured to display error messages as HTML instead of raising them up the stack. Do you have `config.action_dispatch.show_exceptions` set to `true` in `config/environments/test.rb`?

If you're using a standard Rails setup (`show_exceptions` is usually `false` in tests) and a modern version of Capybara, you'll get error messages like the one I pasted above in your test output.

I think the issue seeing exceptions is an issue in your configuration and not a bug with capybara-webkit, so I'm going to close this issue. However, the "broken pipe" error is a crash, which is definitely a bug in webkit_server. Because of the large number of bugs in Qt 4, I'm not willing to invest a lot of time into it, but if you're still seeing those issues after updating to Qt 5, please let me know.

**Closed by jferris** 2015-05-07 15:48 UTC

**Comment by JanStevens** [comment] 2015-05-07 15:53
Yea we had it on `false` *facepalm*

I'll upgrade to Qt5 and If we still see the same issues popping up then I'll create a new issue.

Thanks!
