### ISSUE TITLE
webkit_server processes lingering

### ISSUE THREAD

**Issue by iastazach** [thoughtbot/capybara-webkit#817] opened 2015-07-14 19:14 UTC
Hi there,

When I run my suite of tests, by the end I have tons of webkit_server processes running, even when a test is only using one session.  I've read a few other issues about this, but everything seems to say the issues have been resolved in 1.6.0.  I'm using 1.6.0 and am still having the issue, so I'm wondering if there may still be something wrong, or if it's complete user error.

Here's what I'm doing... in some tests, I initialize several sessions by doing something like: `supplier_session, buyer_session = new_session, new_session`, where `new_session` is defined as:
```
def new_session
  Capybara::Session.new(Capybara.javascript_driver)
end
```
Then I structure my tests as:
```
using_session(supplier_session) { do_something }
using_session(buyer_session) { check_what_was_done}
```
At the end of the test, there then 2 webkit_server processes that don't close until the very end of the entire suite.

Any idea what the issue may be?

Thanks,
Zach

**Comment by mhoran** [comment] 2015-07-15 04:14
The `webkit_server` process will not be reaped until the end of the test suite, so what you're seeing is expected behavior. There's no mechanism via the Capybara API to clean up the processes, so we rely on Ruby closing its file descriptors to determine when to terminate the process.

**Comment by jferris** [comment] 2015-07-20 17:54
This would not be terribly difficult for us to implement, but it's not something that's generally supported by Capybara. If you got buy-in from the Capybara team on a general `stop` or `shutdown` command for sessions, we'd implement it in capybara-webkit. However, I'm not sure how likely that is, because I don't think there's much cost in keeping the extra connection open for the remainder of the test suite.

I'm going to close this, because I don't believe this is a bug and there isn't anything related to this we plan to implement. However, feel free to continue discussing on this thread if you have further thoughts.

**Closed by jferris** 2015-07-20 17:54 UTC

**Comment by iastazach** [comment] 2015-07-20 18:33
Awesome... thanks for the info!  Glad it wasn't just me doing something wrong.  I'm pretty new to this, so that was a very real possibility :-)

**Comment by twalpole** [comment] 2015-07-20 19:49
@iastazach Why are you attempting to generate new sessions for every test?  Capybaras using_session takes the name of a session, so   

    using_session(:buyer_session) { do something } 

should automatically create a new session, associate it to the name :buyer_session, and then reuse the server process created in that session in any other test where you use the session :buyer_session.  In fact, unless you're using your own custom using_session, you may very well be creating 2 sessions each time you use using_session - the one you're creating, and then the one capybara creates based off the text value "name" of the session you created

**Comment by iastazach** [comment] 2015-07-22 16:20
@twalpole Thanks for the tip!  It's working exactly the way you described, and I'm updating my tests now.
