### ISSUE TITLE
Click failed when invisible overlay is present

### ISSUE THREAD

**Issue by aackerman** [thoughtbot/capybara-webkit#629] opened 2014-04-09 17:51 UTC
I have a very specific problem happening between using the select2 library. I'm seeing `Other element would receive the click` issues because select2 has a drop mask that covers the entire page. This makes sense, but the overlay is invisible to the user.

Is there any way to ignore overlapping elements? I know in 99% of all cases this would be a bad idea, but for this 1% case, I'm not sure how to get around the issue other than to execute some JS in my test to hide the element.

**Comment by ajb** [comment] 2015-01-09 20:03
:+1: on this -- it's pretty common practice to use an invisible overlay for styling e.g. `input[type=radio]`.

**Comment by GolfyMcG** [comment] 2015-05-21 12:52
:+1:

**Comment by calleerlandsson** [comment] 2015-06-05 14:26
@jferris, @mhoran Is this issue needed to keep track of this potential feature or should it be closed in favor of pull requests?

**Comment by jferris** [comment] 2015-06-05 20:43
I'm going to close this, since we haven't figured out a solution. The behavior in capybara-webkit is the same as Selenium or Poltergeist when it comes to overlapping elements.

If somebody can think of a good way to tell Capybara "I want to click on this element, but I expect another element to be in the way so actually click on that one," it's probably worth opening a pull request to Capybara itself to figure out how the API should work. However, we can't simply ignore overlapping elements, as it's not clear what the intended behavior is in those cases.

**Closed** 2015-06-12 12:11 UTC

**Comment by benel** [comment] 2016-03-04 19:06
@calleerlandsson @jferris 

This is a real issue.

For example, when using capybara on a Web application with [iToggle](http://labs.engageinteractive.co.uk/itoggle/)-styled checkboxes, one gets:

     Capybara::Webkit::ClickFailed:
        Failed to click element (...) because of overlapping element (...) at position 0, 0; 

The reason for this is that the library "hides" the original checkbox by setting its position to:

    left: -9999px;
    top: -9999px; 

I tried with `:visible => false` but it doesn't work because it is not really `hidden`.

**Comment by jferris** [comment] 2016-03-07 15:53
> The reason for this is that the library "hides" the original checkbox by setting its position to

If the label is matched up with an invisible element, there's no way to click the element for that label, because you can't click invisible things as a user.

If you want to move forward with an unclickable checkbox, you can instead target the element that's actually on the page. I'm not familiar with `iToggle`, but you'd use `find("css-selector").click` to click the visible element.

If capybara-webkit is having trouble finding your elements, it might be a good idea to do an accessibility and usability audit on your form elements. For example, does your page make sense in a screen reader? Can you still navigate your form using only the keyboard? Using JavaScript to re-implement native elements is a common way to break pages, both for automated tests and for some human audiences.

**Comment by benel** [comment] 2016-03-07 15:59
@jferris Thanks for your answer. I replaced "iToggle" with "jQuery Toggles" and it allowed me to use `find("css-selector").click`.
