### ISSUE TITLE
where to whitelist/blacklist urls?

### ISSUE THREAD

**Issue by ashanbrown** [thoughtbot/capybara-webkit#717] opened 2015-01-28 19:53 UTC
It appears that `using_session` will forget about any url whitelist/blacklist that you've set up with calls to `page.driver.block_url` and friends, creating a lot noise.  I'm working around this by calling these methods when the driver is instantiated via `register_driver`:

```ruby
Capybara.register_driver :webkit do |app|
  Capybara::Webkit::Driver.new(app).tap do |driver|
    driver.block_unknown_urls
    driver.allow_url "api.stripe.com/*"
  end
end
```

But this isn't very clean and it doesn't allow any individual test control.  I really want to be able to configure this sort of thing in a before block for a test, although one limitation of that is that I may not even know which driver (I use metadata to change the driver sometime).  I would propose adding some sort of configuration block to capybara webkit that allows the whitelist to be configured immediately prior to running an each example.  Here's an outline of how it might be implemented:

```ruby
module CapybaraSetupDriverHelper
  def append_driver_setup(&block)
    (@_setup_driver_procs ||= []) << block
  end
end

RSpec.configure do |config|
  config.include CapybaraSetupDriverHelper, type: :feature
end

Capybara.register_driver :webkit do |app|
  Capybara::Webkit::Driver.new(app).tap do |driver|
    driver_setup_blocks = RSpec.current_example.example_group_instance.
      instance_variable_get(:@_setup_driver_procs) || []
    driver_setup_blocks.each do |block|
      block.call(driver)
    end
  end
end
```

Then my test setup just looks like:

```ruby
RSpec.configure do |config|
  config.before type: :feature do
    append_driver_setup do |driver|
      driver.block_unknown_urls
      driver.allow_url "api.stripe.com"
    end
  end
end
```

Ultimately this looks to me like behavior that capybara itself could support more generally by adding a common callback mechanism after a driver is instantiated, but the management of driver setup is something that should be done within capybara (seems like this might belong in a missing rspec-capybara gem).  I'd welcome any thoughts on this issue.  Thanks.

**Comment by mhoran** [comment] 2015-01-28 20:20
Allowed URLs are reset between specs, via `Driver#reset!`. I have the following in my `spec_helper.rb`, which initializes the whitelist for each spec:

```ruby
  config.before :each, :js, type: :feature do |example|
    # Everything is terrible. js: true in config.before will run if the js tag
    # is present in the spec declaration, regardless of the value.
    if example.metadata[:js]
      page.driver.block_unknown_urls
      page.driver.allow_url('api.stripe.com')
      page.driver.allow_url('js.stripe.com')
    end
  end
```

I think there are two issues here. One is a question on how to maintain the whitelist. It was intended to be set up and torn down between specs, so a global configuration is not appropriate. However, as you point out, `.using_session` will not work with a before block, as the session will be initialized on demand.

For the latter issue, I think we need a way to hook into session initialization if configuration is to be done in a before block. Alternatively, the whitelist could be set up in the `.using_session` block, though I realize this would lead to duplication.

**Comment by dontfidget** [comment] 2015-01-30 19:44
I didn't realize that the whitelist was being reset between specs even though the driver itself is not rebuilt, and that in fact was causing problems with my suggestion.  Currently, I'm doing this:

```
setup_url_whitelist = lambda do |driver|
  driver.block_unknown_urls
  driver.allow_url "api.stripe.com"
end

RSpec.configure do |config|
  config.before :example, :js, type: :feature do |example|
    if example.metadata[:js] && Capybara.current_driver == :webkit
      setup_url_whitelist.call(page.driver)
    end
  end
end

Capybara.register_driver :webkit do |app|
  Capybara::Webkit::Driver.new(app).tap do |driver|
    setup_url_whitelist.call(driver)
  end
end
```

I think this probably breaks down if a non-default session driver gets re-used.  I'm not sure that `using_session` is even the right place to run the url whitelist setup code.  For one thing, you can change the session without calling `using_session` just by setting `Capybara.session_name`.  Maybe you could have a list of drivers that have been set up for the current session.  Whenever you reset each driver, which presumably you do for all drivers in the session pool, you'd clear that list.  Then when you change drivers and pick one that has not been set up, you execute an optional callback on that driver.

**Comment by jferris** [comment] 2015-02-02 15:35
I think it makes sense to either:

1. Move some configuration options like URL whitelisting into global settings which don't reset.
2. Continue to scope settings to a particular session.

I personally have never been in a situation where option 1 would be a problem.

**Comment by mhoran** [comment] 2015-02-03 01:22
Here are the relevant bits for RSpec from the Capybara RSpec configuration block: 

```ruby
config.after do
  if self.class.include?(Capybara::DSL)
    Capybara.reset_sessions!
    Capybara.use_default_driver
  end
end
```

After each test, `Capybara.reset_sessions!` triggers `Driver#reset!` via `Session#reset!`. Note the driver is only reset if it has been "touched".

With either solution, we still have the problem of how to initialize the blacklist per session. I don't think there are any configuration callbacks that make that possible. Option one would make sense if we had a way to initialize a global whitelist for all sessions, but a new session will initialize a new `Driver`, with no whitelist.

We could expose these "global" options via `Capybara::Webkit::Driver`, as we do with the `stdout` option:

```ruby
Capybara.register_driver :webkit do |app|
  Capybara::Driver::Webkit.new(
    app,
    :allowed_urls => ['example.com'],
    block_unknown_urls: true
  )
end
```

However, this still seems a bit clunky.

**Comment by jferris** [comment] 2015-02-03 14:19
We could add a `Capybara::WebKit.configure do |config|` sort of thing for global defaults.

**Comment by asafbrukarz** [comment] 2015-02-04 00:22
Just want to add our use case here as we're receiving a lot of noise from capybara_webkit. 

We use [billy](https://github.com/oesmith/puffing-billy) and [vcr](https://github.com/vcr/vcr) to proxy and cache requests for our Cucumber integration tests. 

These gems already have URL/domain whitelists and request blocking. We configure the allowed/ignored domains for each gem in their respective initialisers. 

Setting the whitelist to match the other gems before each feature feels a bit terse to me, so we'd prefer to have the option of `allow_unkown_urls` to silence the log, or allow us to configure a global whitelist as above that we could keep in sync with our other gems.

Thanks.

**Comment by twalpole** [comment] 2015-02-04 01:02
@jferris @mhoran  Since poltergeist is also adding URL blacklisting,  is this something you think would be worth having a unified configuration for in Capybara?

**Comment by mhoran** [comment] 2015-02-04 01:37
Absolutely. We originally had a blacklist, but recently switched to warning for "unknown" (non-localhost) URLs by default. This was due to user complaints about slow tests due to remote requests. 

We have a switch that will block remote URLs instead of warn. This seems preferable to blacklisting, which I was hoping to deprecate.

The "whitelist" can be configured via an `allow_url` driver method, which will either silence warnings for the URL, or permit remote requests, depemding on configuration.

Personally, I feel a whitelist leads to the expected behavior, where slow external dependencies are disabled by default. Happy to discuss further, but these are my observations after previously only supporting a blacklist.

**Comment by jferris** [comment] 2015-02-04 14:52
@asafbrukarz you can allow a URL of `*` to whitelist everything.

**Comment by jferris** [comment] 2015-02-04 14:56
I agree with everything @mhoran said about whitelists and blacklists. Blacklists are pretty hard to nail down and aren't generally useful for testing, as the list you want is generally small (just local requests, maybe you add one remote host) and the list you don't want is large (everything else on the Internet).

**Comment by asafbrukarz** [comment] 2015-02-05 22:37
@jferris Thanks - I didn't realise that * would whitelist everything (which is essentially what we're after). However, as the list is reset when the driver is reset, we'd have to add this into a `Before` method to run before each spec. It would be simpler to configure this globally during initialization.

**Comment by coneill6937** [comment] 2015-02-09 23:15
very similar to one of mhoran's suggestions, I got the "Request to unknown URL"  messages to stop by putting this block of code in my spec_helper.rb file:   
```ruby
RSpec.configure do |config|
    config.before(:each) do
        page.driver.allow_url("testing-alexpbf.jellyvisionlab.com")
        page.driver.allow_url("d3cmxeovzo2voo.cloudfront.net")
        page.driver.allow_url("d1yywq8fo7k142.cloudfront.net")
        page.driver.allow_url("www.google-analytics.com")
        page.driver.allow_url("josef.jellyvisionlab.com")
        page.driver.allow_url("assets.zendesk.com")
    end
end
```

**Comment by jferris** [comment] 2015-02-10 14:36
@coneill6937 do you actually want to load things like Google Analytics during your integration tests? If not, you probably want to use `page.driver.block_unknown_urls` and then just use `allow_urls` with domains which are necessary to run the tests.

**Comment by coneill6937** [comment] 2015-02-10 23:05
@jferris good point.  thanks.

**Comment by jferris** [comment] 2015-04-10 21:30
I've opedn #756 to address this.

**Closed by jferris** 2015-04-10 21:30 UTC

**Comment by onebree** [comment] 2015-04-14 20:07
@jferris  Thank you for the upcoming PR. Looking forward to it!

@mhoran In reply to your [comment](https://github.com/thoughtbot/capybara-webkit/issues/717#issuecomment-71908159), sometimes I label an entire spec as using JS, especially with nested forms, like so: `feature "Exercise page", js: true do`, and proceed with context/background.

Would your solution from the comment work with such specs?

**Comment by mhoran** [comment] 2015-04-15 16:08
@onebree, yes, it should work regardless of where the `:js` tag is applied. The `config.before` block runs before each individual spec, and the metadata propagates downward to each scenario.

**Comment by onebree** [comment] 2015-04-15 17:13
@mhoran thank you... I actually downgraded back to 1.3.1, because the block_urls error does not appear with that gem.

**Comment by toothrot** [comment] 2015-10-01 16:26
In our app we ended up doing the following in our spec_helper:

```ruby
config.after(:example, js: true) do
  # Try to wait for any pending browser requests to finish before database cleaner.
  visit('/health_check')
  expect(page).to have_content('health_check')
end
```

Resetting the driver didn't ensure that any currently processing requests on the test server were done, so database cleaner would still cause issues occasionally. 

In this configuration, adding a blocking request at the end of the test run before database cleaner seems to do the trick without adding too much time to our test run.

**Comment by jferris** [comment] 2015-10-01 17:43
@toothrot in more recent versions of capybara-webkit, the driver tries to end all ongoing requests when it resets. Can you see if your workaround is still necessary on the latest version?

**Comment by toothrot** [comment] 2015-10-02 01:49
@jferris thanks for the response! we're on the latest. 

capybara-webkit is actually doing a great job of ending its requests. My best guess is that it's the requests that have hit the rails server and are processing during rspec teardown that seem to cause issue. this gives us a way to verify via starting another blocking request that it is no longer an issue. Since we're using superagent, we don't have a great way of asserting that there are not any XHR's processing other than trying to issue another request manually.

**Comment by DenisPopov15** [comment] 2016-02-10 09:26
@mhoran can you give me a tip, why `config.allow_url("bam.nr-data.net")` don't work? Even when I run only 1 test, I always see: `Request to unknown URL: https://bam.nr-data.net/...........`
