### ISSUE TITLE
`type` property of file field is empty

### ISSUE THREAD

**Issue by dougal** [thoughtbot/capybara-webkit#704] opened 2015-01-06 12:23 UTC
When a file is selected using a file field, the type of that field is empty. Tested by outputting to the console the type, after the file is selected.

Safari:

```
ContentType: video/mp4
```

Webkit-Capybara:

```
ContentType: 
```

If it is helpful I can put together a minimal failing example application that shows this behaviour.

**Comment by jferris** [comment] 2015-01-07 14:57
@dougal a minimal failing example would be very helpful.

**Comment by dougal** [comment] 2015-01-07 20:51
Example application with failing spec demonstrating the above: https://github.com/dougal/capybara-webkit-issue-704

Quick-start:

    git clone https://github.com/dougal/capybara-webkit-issue-704.git && cd capybara-webkit-issue-704.git && bundle install && bundle exec rake spec

Thanks.

**Comment by calleerlandsson** [comment] 2015-06-12 12:28
Using @dougal's example, I can reliably reproduce this.

**Comment by twalpole** [comment] 2017-10-18 19:35
Closing due to age. We can reopen if this is still an issue with current releases.

**Closed by twalpole** 2017-10-18 19:35 UTC

**Comment by dougal** [comment] 2017-10-21 16:44
Tested with `capybara-webkit 1.14.0`. Issue is now fixed.

Thanks to whoever fixed this issue either here, in Capybara, or Webkit. :)
