### ISSUE TITLE
Capybara::Webkit::ConnectionError occurs intermittently

### ISSUE THREAD

**Issue by tmertens** [thoughtbot/capybara-webkit#845] opened 2015-09-30 18:25 UTC
We see intermittent failures due to `Capybara::Webkit::ConnectionError` (see stack trace below) in our CI environment (Solano).  It happens around 1:10 builds which is more like 1:160 or higher executions of rspec, since each build is split across 16 workers.  But, since it ultimately results in as much as 10% of our builds failing it's a fairly high visible issue for us.

I benchmarked `discover_port` locally to see if it was just hitting close to the timeout but it was very fast: `0.000000   0.000000   0.000000 (  0.096527)`, so it's unclear why this would be timing out at all in CI.  I'm wondering if anyone can give insight into this issue and why it would hit the timeout if normal execution time is so fast?

```
     Failure/Error: Unable to find matching line from backtrace
     Capybara::Webkit::ConnectionError:
       /mnt/home/u5196/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.0/bin/webkit_server failed to start after 15 seconds.
     # /mnt/home/u5196/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.0/lib/capybara/webkit/connection.rb:95:in `discover_port'
     # /mnt/home/u5196/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.0/lib/capybara/webkit/connection.rb:74:in `start_server'
     # /mnt/home/u5196/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.0/lib/capybara/webkit/connection.rb:31:in `initialize'
     # /mnt/home/u5196/bundle/ruby/2.2.0/gems/capybara-webkit-1.7.0/lib/capybara/webkit/driver.rb:14:in `new'
```

**Comment by tmertens** [comment] 2015-10-26 22:05
We are still seeing this on a regular basis, even after retrying the connection ourselves:

```ruby
require 'capybara/webkit'

module Support
  module CapybaraWebkitConnectionRetry
    def measure
      value = nil
      bm = Benchmark.measure {
        value = yield
      }
      Kernel.puts "#{caller_locations(1,1)[0].label}: #{bm}"
      value
    end

    def start_server
      tries = 0
      begin
        measure {
          super
        }
      rescue ::Capybara::Webkit::ConnectionError => e
        raise e unless tries < 3
        tries += 1
        retry
      end
    end
  end
end

Capybara::Webkit::Connection.prepend(Support::CapybaraWebkitConnectionRetry)
```

Any suggestions?

**Comment by taylorzr** [comment] 2015-11-25 14:46
I'm seeing this issue as well, any updates?

**Comment by iqnivek** [comment] 2016-01-28 16:05
I'm running into with Solano CI as well (capybara 1.7.1, qt5) - any tips on how to diagnose the issue would be appreciated!

**Comment by tmertens** [comment] 2016-01-28 19:59
I've also seen this occur intermittently on circleci with Qt 5.5.1:

```
QMake version 3.0
Using Qt version 5.5.1 in /opt/qt55/lib
```

**Comment by mkiddAvantCredit** [comment] 2016-01-28 22:29
So I was able to reproduce this locally.

I ran the test locally as I've done many times today and then received the "Capybara::Webkit::ConnectionError".

Digging a bit deeper into capybara-webkit it was found that [line 80](https://github.com/thoughtbot/capybara-webkit/blob/master/lib/capybara/webkit/connection.rb#L80) is attempting to open the server via Open3. 

The SERVER_PATH provided however yielded the following error:

`mbp-0743:avant-basic USER_NAME$ /Users/USER_NAME/.rvm/gems/ruby-2.2.2@avant_basic/gems/capybara-webkit-1.7.0/bin/webkit_server
dyld: Library not loaded: /usr/local/opt/qt5/lib/QtWebKitWidgets.framework/Versions/5/QtWebKitWidgets
  Referenced from: /Users/USER_NAME/.rvm/gems/ruby-2.2.2@avant_basic/gems/capybara-webkit-1.7.0/bin/webkit_server
  Reason: image not found
Trace/BPT trap: 5
`

for reference this is the qmake -v result

`QMake version 3.0
Using Qt version 5.5.1 in /usr/local/Cellar/qt5/5.5.1_2/lib`

**Comment by iqnivek** [comment] 2016-02-01 20:41
Solano troubleshooting docs indicate that it could have something to do with the thin webserver: http://docs.solanolabs.com/HandlingFailures/browser-based-integration-tests/#capybara-hangs-when-using-capybara-webkit. I'll try using webrick to see if that changes anything.

**Comment by nhance** [comment] 2016-05-10 18:13
I added some additional comments on #643 as I am currently seeing this issue.

For me, it is related to `QApplication::QApplication`

**Comment by nhance** [comment] 2016-05-10 18:29
Make sure you are running this with `xvfb-run` if you don't have a X11 server on your machine. This error pops up and will leave you hunting for the answer when it's already documented here:

https://github.com/thoughtbot/capybara-webkit#ci

**Comment by jferris** [comment] 2016-06-02 14:20
It seems like this may be an issue with how Qt tries to find an X11 connection when it doesn't see the usual `XAUTHORITY`. I wonder if we could bail earlier on Linux when that isn't found?

**Comment by jonahwh** [comment] 2016-09-16 20:10
I've tried `xvfb-run` and the `headless` gem, and the issue has continued to occur with either solution.

**Comment by daveomcd** [comment] 2016-09-22 19:47
I'm also getting this issue.  My seems to happen randomly.

**Comment by arielscherman** [comment] 2017-01-13 00:22
I run into the same issue when setting **circleci** app. In case it helps, my problem was that I had to add the dependency of **qt5** to the **circle.yml** file.

This is the file that worked for me:

```
machine:
  timezone:
    America/Los_Angeles

dependencies:
  pre:
    - sudo add-apt-repository ppa:beineri/opt-qt542-trusty -y
    - sudo apt-get update -y; true
    - sudo apt-get install -y qt54webkit libwebkit-dev libgstreamer0.10-dev
    - echo "/opt/qt54/bin/qt54-env.sh" >> ~/.circlerc

```

**Comment by twalpole** [comment] 2017-11-09 02:05
Closing this due to age, and that it appears to have been a number of different issues for people.  If anyone is still having the issue with the current master branch and can provide a reproducible example please open a new issue.

**Closed by twalpole** 2017-11-09 02:05 UTC
